In [1]:
cd /gpfs/group/smr48/default/io

/gpfs/group/smr48/default/io

In [2]:
import pandas as pd
from pathlib import Path
import os
import numpy as np
import csv
import argparse
import datetime
import sys

In [3]:
o_files = os.listdir('/gpfs/group/smr48/default/io/_Original/')


# big_cnts = ['russia', 'iran', 'egypt','cuba', 'china', 'turkey', 'saudi_arabia', 'serbia', 'venezuela']
big_cnts = ['venezuela']

o_files.sort()

In [4]:
o_files

['original_armenia_1.pkl',
 'original_bangladesh_1.pkl',
 'original_catalonia_1.pkl',
 'original_china_mast.pkl',
 'original_cuba_mast.pkl',
 'original_ecuador_1.pkl',
 'original_egypt_mast.pkl',
 'original_honduras_1.pkl',
 'original_indonesia_1.pkl',
 'original_iran_mast.pkl',
 'original_russia_mast.pkl',
 'original_saudi_arabia_mast.pkl',
 'original_serbia_mast.pkl',
 'original_spain_1.pkl',
 'original_thailand_1.pkl',
 'original_turkey_mast.pkl',
 'original_uae_1.pkl',
 'original_uae_egypt_1.pkl',
 'original_venezuela_1.pkl',
 'original_venezuela_2.pkl',
 'original_venezuela_3.pkl',
 'original_venezuela_4.pkl',
 'original_venezuela_5.pkl',
 'subfiles']

In [ ]:

for c in big_cnts: 
    print(c)
    print('O')
    matching = [s for s in o_files if c in s]
    df_master = pd.DataFrame(columns=['tweetid', 'userid', 'user_display_name', 'user_screen_name',
      'user_reported_location', 'user_profile_description',
      'user_profile_url', 'follower_count', 'following_count',
      'account_creation_date', 'account_language', 'tweet_language',
      'tweet_text', 'tweet_time', 'tweet_client_name', 'in_reply_to_userid',
      'in_reply_to_tweetid', 'quoted_tweet_tweetid', 'is_retweet',
      'retweet_userid', 'retweet_tweetid', 'latitude', 'longitude',
      'quote_count', 'reply_count', 'like_count', 'retweet_count', 'hashtags',
      'urls', 'user_mentions', 'poll_choices'])
    print(len(df_master))
    for f in matching: 
        df = pd.read_pickle('/gpfs/group/smr48/default/io/_Original/{}'.format(f))
        df_master = pd.concat([df_master, df], ignore_index=True)
        print(len(df_master))
        del df
    df_master = df_master.drop_duplicates(subset=['tweetid'], keep='first')
    df_master.to_pickle('/gpfs/group/smr48/default/io/_Original/original_{}_mast.pkl'.format(c))
    del df_master

venezuela
O
0
1904787
3448689
5336439
6942436
8301554

In [4]:
df = pd.read_pickle('_Original/original_armenia_1.pkl')
df.columns

Index(['tweetid', 'userid', 'user_display_name', 'user_screen_name',
       'user_reported_location', 'user_profile_description',
       'user_profile_url', 'follower_count', 'following_count',
       'account_creation_date', 'account_language', 'tweet_language',
       'tweet_text', 'tweet_time', 'tweet_client_name', 'in_reply_to_userid',
       'in_reply_to_tweetid', 'quoted_tweet_tweetid', 'is_retweet',
       'retweet_userid', 'retweet_tweetid', 'latitude', 'longitude',
       'quote_count', 'reply_count', 'like_count', 'retweet_count', 'hashtags',
       'urls', 'user_mentions', 'poll_choices'],
      dtype='object')

In [3]:
folder = 'armenia'
number = 1


df = pd.read_pickle('_Parsed/{}_parsed_{}.pkl'.format(folder, number))



df.tweetid = df.tweetid.apply(str)
df.userid = df.userid.apply(str)
df.in_reply_to_userid = df.in_reply_to_userid.apply(str)
df.retweet_userid = df.retweet_userid.apply(str)

# # Load all Tweets completed by IO actors
# masterTweets = pd.read_csv('_masterTweetList_2021-05.csv')
# masterTweets["m_userid"]= masterTweets["m_userid"].astype(str) 
# masterTweets["m_tweetid"]= masterTweets["m_tweetid"].astype(str) 
       
masterUIDs = pd.read_csv('_masterUIDs_2021-05.csv')
masterUIDs = masterUIDs[masterUIDs['id']!='userid']
masterUIDs.id = masterUIDs.id.apply(str)

IOactors = []


####### RETWEET Actors #######

In [4]:
dfRT_all = df[(df['quoted_tweet_tweetid'] == '') | (df['quoted_tweet_tweetid'] == 'nan') | (df['quoted_tweet_tweetid'] == 'NaN') | (df['quoted_tweet_tweetid'].isnull())]

                
                
dfRT_all[dfRT_all['quoted_tweet_tweetid'].isnull()]
dfRT_all = dfRT_all.drop_duplicates()
dfRT1 = dfRT_all[(dfRT_all['is_retweet'] != 'false') & (dfRT_all['is_retweet'] != 'FALSE') & (dfRT_all['is_retweet']!=False)]

In [25]:
dfRT_all.retweet_tweetid.notnull()

0        False
1        False
2        False
3        False
4        False
         ...
72955     True
72956     True
72957     True
72958     True
72959     True
Name: retweet_tweetid, Length: 72291, dtype: bool

In [34]:
####### Original Actors #######
dfOrig_all = dfRT_all[((dfRT_all['is_retweet'] == False) &  (dfRT_all['retweet_userid'] == 'nan') & (dfRT_all['retweet_tweetid'].isnull()))]
# dfOrig_all
# dfOrig_all = dfOrig_all.drop_duplicates(subset='tweetid', keep='first')

dfOrig_all

,tweetid,userid,user_display_name,user_screen_name,user_reported_location,user_profile_description,user_profile_url,follower_count,following_count,account_creation_date,...,latitude,longitude,quote_count,reply_count,like_count,retweet_count,hashtags,urls,user_mentions,poll_choices
0,1331706590525874184,qXsKFeuypKnamstyGzyIyb5ESxeYVrF4lfj+DoNEiBI=,qXsKFeuypKnamstyGzyIyb5ESxeYVrF4lfj+DoNEiBI=,qXsKFeuypKnamstyGzyIyb5ESxeYVrF4lfj+DoNEiBI=,Azerbaijan,https://t.co/7q3bPlI5Ne является независимым и...,https://t.co/TY3gz33nIF,0,0,2020-11-23,...,absent,absent,0.0,0.0,0.0,0.0,"['haqqinaz', 'haqqin', 'haqqinz']",['https://haqqin.az/news/194712'],[],NaN
1,1100358276435398656,2rg8fiE11JB8Bh69A6aJWeRSBPcGTAmK8wnpFpH0=,2rg8fiE11JB8Bh69A6aJWeRSBPcGTAmK8wnpFpH0=,2rg8fiE11JB8Bh69A6aJWeRSBPcGTAmK8wnpFpH0=,Azerbaijan,I’ve learned I don’t know anything. Have also...,NaN,145,530,2019-02-21,...,absent,absent,0.0,0.0,0.0,0.0,"['Azerbaijan', 'shareforkhojaly', 'justicefork...",[],[],NaN
2,1100389340914569216,vrJSje34LOxmhLf7y0QqVdtulQZBm6QfOtxswidhrs=,vrJSje34LOxmhLf7y0QqVdtulQZBm6QfOtxswidhrs=,vrJSje34LOxmhLf7y0QqVdtulQZBm6QfOtxswidhrs=,"Agri, Turkey",Love the life to its fullest\n#Shareforkhojaly...,NaN,146,423,2019-02-21,...,absent,absent,1.0,0.0,0.0,0.0,"['shareforkhojaly', 'justiceforkhojaly']",[],[],NaN
3,724982683118358528,uqU5V82g6lpOgJjvDGLIA4LEFT2wGmque+vYhRUTk=,uqU5V82g6lpOgJjvDGLIA4LEFT2wGmque+vYhRUTk=,uqU5V82g6lpOgJjvDGLIA4LEFT2wGmque+vYhRUTk=,Azerbaijan,Lieutenant General is an Azerbaijani politicia...,https://t.co/06ojhMm2e6,112,15,2016-04-10,...,absent,absent,0.0,0.0,0.0,0.0,[],['http://www.unaoc.org/wp-content/uploads/2016...,[],NaN
4,728142042765742080,uqU5V82g6lpOgJjvDGLIA4LEFT2wGmque+vYhRUTk=,uqU5V82g6lpOgJjvDGLIA4LEFT2wGmque+vYhRUTk=,uqU5V82g6lpOgJjvDGLIA4LEFT2wGmque+vYhRUTk=,Azerbaijan,Lieutenant General is an Azerbaijani politicia...,https://t.co/06ojhMm2e6,112,15,2016-04-10,...,absent,absent,0.0,0.0,0.0,0.0,['Azerbaijan'],['http://bit.ly/24tbEqN'],[],NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
72785,608974272246128640,Rgex8nPtn9Y4bvWf9RMb8yI2GGWP65yTXb+9ZygHU=,Rgex8nPtn9Y4bvWf9RMb8yI2GGWP65yTXb+9ZygHU=,Rgex8nPtn9Y4bvWf9RMb8yI2GGWP65yTXb+9ZygHU=,Azerbaijan,Minister of Foreign Affairs of the Republic of...,https://t.co/RI9sLBiat9,527,134,2014-11-20,...,absent,absent,0.0,0.0,0.0,0.0,['today_az'],['http://bit.ly/1Hv4LZm'],[],NaN
72786,600641916007370752,Rgex8nPtn9Y4bvWf9RMb8yI2GGWP65yTXb+9ZygHU=,Rgex8nPtn9Y4bvWf9RMb8yI2GGWP65yTXb+9ZygHU=,Rgex8nPtn9Y4bvWf9RMb8yI2GGWP65yTXb+9ZygHU=,Azerbaijan,Minister of Foreign Affairs of the Republic of...,https://t.co/RI9sLBiat9,527,134,2014-11-20,...,absent,absent,0.0,0.0,0.0,0.0,['today_az'],['http://bit.ly/1S6v7ov'],[],NaN
72787,664757737704714241,Rgex8nPtn9Y4bvWf9RMb8yI2GGWP65yTXb+9ZygHU=,Rgex8nPtn9Y4bvWf9RMb8yI2GGWP65yTXb+9ZygHU=,Rgex8nPtn9Y4bvWf9RMb8yI2GGWP65yTXb+9ZygHU=,Azerbaijan,Minister of Foreign Affairs of the Republic of...,https://t.co/RI9sLBiat9,527,134,2014-11-20,...,absent,absent,0.0,0.0,0.0,0.0,['today_az'],['http://bit.ly/1HCeI9n'],[],NaN
72788,777532499391942658,Rgex8nPtn9Y4bvWf9RMb8yI2GGWP65yTXb+9ZygHU=,Rgex8nPtn9Y4bvWf9RMb8yI2GGWP65yTXb+9ZygHU=,Rgex8nPtn9Y4bvWf9RMb8yI2GGWP65yTXb+9ZygHU=,Azerbaijan,Minister of Foreign Affairs of the Republic of...,https://t.co/RI9sLBiat9,527,134,2014-11-20,...,absent,absent,0.0,0.0,0.0,0.0,['today_az'],['http://bit.ly/2cK9JoR'],[],NaN
72789,773075238162608129,Rgex8nPtn9Y4bvWf9RMb8yI2GGWP65yTXb+9ZygHU=,Rgex8nPtn9Y4bvWf9RMb8yI2GGWP65yTXb+9ZygHU=,Rgex8nPtn9Y4bvWf9RMb8yI2GGWP65yTXb+9ZygHU=,Azerbaijan,Minister of Foreign Affairs of the Republic of...,https://t.co/RI9sLBiat9,527,134,2014-11-20,...,absent,absent,0.0,0.0,0.0,0.0,['today_az'],['http://bit.ly/2cwf3xq'],[],NaN

In [70]:
dfRT1

,tweetid,userid,user_display_name,user_screen_name,user_reported_location,user_profile_description,user_profile_url,follower_count,following_count,account_creation_date,...,latitude,longitude,quote_count,reply_count,like_count,retweet_count,hashtags,urls,user_mentions,poll_choices
255,1101032560120004608,rOr0az+xkI49HIn0VwU6R1Som+obkg6E84AqY5hnoTo=,rOr0az+xkI49HIn0VwU6R1Som+obkg6E84AqY5hnoTo=,rOr0az+xkI49HIn0VwU6R1Som+obkg6E84AqY5hnoTo=,"baku, az","I'm Cabir, an Architect👷‍♂️ working in Baku 🇦🇿",NaN,134,426,2019-02-21,...,absent,absent,0.0,0.0,0.0,0.0,[],[],['9tv1gRACFz8IPY6lCkXCgaXEJh1Ol2Fk78bhuCGhyA='],NaN
256,1101031776670101504,p8PbTRSSnu3Re1jI+c33x2TdFAKbqe6P5ZSQGmlbQ=,p8PbTRSSnu3Re1jI+c33x2TdFAKbqe6P5ZSQGmlbQ=,p8PbTRSSnu3Re1jI+c33x2TdFAKbqe6P5ZSQGmlbQ=,Azerbaijan,Buraya necə gəlmişəm??? 😅,NaN,100,414,2019-02-21,...,absent,absent,0.0,0.0,0.0,0.0,[],[],['9tv1gRACFz8IPY6lCkXCgaXEJh1Ol2Fk78bhuCGhyA='],NaN
840,1101032817377624064,vrJSje34LOxmhLf7y0QqVdtulQZBm6QfOtxswidhrs=,vrJSje34LOxmhLf7y0QqVdtulQZBm6QfOtxswidhrs=,vrJSje34LOxmhLf7y0QqVdtulQZBm6QfOtxswidhrs=,"Agri, Turkey",Love the life to its fullest\n#Shareforkhojaly...,NaN,146,423,2019-02-21,...,absent,absent,0.0,0.0,0.0,0.0,[],[],['9tv1gRACFz8IPY6lCkXCgaXEJh1Ol2Fk78bhuCGhyA='],NaN
843,1098906852891545601,Tf0FY7EDYEUVzBsJNSLmYJ0nBSU4Z38qsQxp48GpxA=,Tf0FY7EDYEUVzBsJNSLmYJ0nBSU4Z38qsQxp48GpxA=,Tf0FY7EDYEUVzBsJNSLmYJ0nBSU4Z38qsQxp48GpxA=,Azerbaijan,I have three years exerience in creating prof...,NaN,65,440,2019-02-21,...,absent,absent,0.0,0.0,0.0,0.0,"['Pomegranate', 'Azerbaijan']",[],['2211871536'],NaN
1821,1101030210361847808,Dw3BUtxw5YA0q9KN9iSzs8OfJBlwR6yd1abnKmfds=,Dw3BUtxw5YA0q9KN9iSzs8OfJBlwR6yd1abnKmfds=,Dw3BUtxw5YA0q9KN9iSzs8OfJBlwR6yd1abnKmfds=,"Baku, Azerbaijan","Dancer, model, photographer📸\n#Justiceforkhoja...",NaN,204,557,2019-02-22,...,absent,absent,0.0,0.0,0.0,0.0,[],[],['9tv1gRACFz8IPY6lCkXCgaXEJh1Ol2Fk78bhuCGhyA='],NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
72955,1101031612240809985,p8PbTRSSnu3Re1jI+c33x2TdFAKbqe6P5ZSQGmlbQ=,p8PbTRSSnu3Re1jI+c33x2TdFAKbqe6P5ZSQGmlbQ=,p8PbTRSSnu3Re1jI+c33x2TdFAKbqe6P5ZSQGmlbQ=,Azerbaijan,Buraya necə gəlmişəm??? 😅,NaN,100,414,2019-02-21,...,absent,absent,0.0,0.0,0.0,0.0,[],[],['1L0qn8rgg4bi6tCYH934gRpAQG59vTUg9kPubBzxM='],NaN
72956,1101031278038712323,2rg8fiE11JB8Bh69A6aJWeRSBPcGTAmK8wnpFpH0=,2rg8fiE11JB8Bh69A6aJWeRSBPcGTAmK8wnpFpH0=,2rg8fiE11JB8Bh69A6aJWeRSBPcGTAmK8wnpFpH0=,Azerbaijan,I’ve learned I don’t know anything. Have also...,NaN,145,530,2019-02-21,...,absent,absent,0.0,0.0,0.0,0.0,[],[],['1L0qn8rgg4bi6tCYH934gRpAQG59vTUg9kPubBzxM='],NaN
72957,1101030493246668801,eo0xpq4n+8U5Uy2FZlrcxtBEd0gldAZyDPDT+7D+wY=,eo0xpq4n+8U5Uy2FZlrcxtBEd0gldAZyDPDT+7D+wY=,eo0xpq4n+8U5Uy2FZlrcxtBEd0gldAZyDPDT+7D+wY=,"Baku, Azerbaijan",Manager @Absheron Yacht Club\n#Justiceforkhoja...,NaN,141,579,2019-02-21,...,absent,absent,0.0,0.0,0.0,0.0,[],[],['1L0qn8rgg4bi6tCYH934gRpAQG59vTUg9kPubBzxM='],NaN
72958,1101031071163039744,e7MA8928eiTvHTGw7lNORtEVx85xr8YkmbJuYv80=,e7MA8928eiTvHTGw7lNORtEVx85xr8YkmbJuYv80=,e7MA8928eiTvHTGw7lNORtEVx85xr8YkmbJuYv80=,Azerbaijan,Həyat belə bir şeydir .....\n#Justiceforkhojal...,NaN,226,543,2019-02-23,...,absent,absent,0.0,0.0,0.0,0.0,[],[],['1L0qn8rgg4bi6tCYH934gRpAQG59vTUg9kPubBzxM='],NaN
72959,1101031128528498689,e7MA8928eiTvHTGw7lNORtEVx85xr8YkmbJuYv80=,e7MA8928eiTvHTGw7lNORtEVx85xr8YkmbJuYv80=,e7MA8928eiTvHTGw7lNORtEVx85xr8YkmbJuYv80=,Azerbaijan,Həyat belə bir şeydir .....\n#Justiceforkhojal...,NaN,226,543,2019-02-23,...,absent,absent,0.0,0.0,0.0,0.0,['USSR'],[],['1L0qn8rgg4bi6tCYH934gRpAQG59vTUg9kPubBzxM='],NaN

In [4]:
df = pd.read_pickle('uae_egypt_parsed_1.pkl')
# df.columns

df['user_mentions'] = df['user_mentions'].str.replace(']', '')
df['user_mentions'] = df['user_mentions'].str.replace('[', '')
df['user_mentions'] = df['user_mentions'].str.replace(' ', '')
df['user_mentions'] = df['user_mentions'].str.replace('\'', '')
df2 = df.copy()
df2 = df2.join(df2.pop('user_mentions').str.split(',',expand=True))
df2.set_index(['tweetid', 'userid', 'user_display_name', 'user_screen_name',
                'user_reported_location', 'user_profile_description','user_profile_url', 
                'follower_count', 'following_count','account_creation_date', 'account_language', 
                'tweet_language','tweet_text', 'tweet_time', 'tweet_client_name', 
                'in_reply_to_userid','in_reply_to_tweetid', 'quoted_tweet_tweetid', 
                'is_retweet','retweet_userid', 'retweet_tweetid', 'latitude', 
                'longitude','quote_count', 'reply_count', 'like_count', 
                'retweet_count', 'hashtags','urls', 'poll_choices']).stack().reset_index(level=[0,1],name='mention')

<ipython-input-4-57cdc9e60d97>:4: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will*not* be treated as literal strings when regex=True.
  df['user_mentions'] = df['user_mentions'].str.replace(']', '')
<ipython-input-4-57cdc9e60d97>:5: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will*not* be treated as literal strings when regex=True.
  df['user_mentions'] = df['user_mentions'].str.replace('[', '')

,tweetid,userid,user_display_name,user_screen_name,user_reported_location,user_profile_description,user_profile_url,follower_count,following_count,account_creation_date,...,longitude,quote_count,reply_count,like_count,retweet_count,hashtags,urls,poll_choices,variable,value
26,1130636632942620673,OnyzKfd1l2LdVEaqG8DxYkgk8xhckHnwsUKS6Wd6ZRw=,OnyzKfd1l2LdVEaqG8DxYkgk8xhckHnwsUKS6Wd6ZRw=,OnyzKfd1l2LdVEaqG8DxYkgk8xhckHnwsUKS6Wd6ZRw=,Libya,ليبي و افتخر 🇱🇾🇱🇾,NaN,149,430,2015-10-14,...,absent,0.0,0.0,0.0,0.0,"['قطر', 'الشعب_السوداني', 'اطردوا_مخابرات_قطر_...",[],NaN,0,2946753318
170,1119286214375419905,v9Pn0seyZOtp1Tb3UJ4NQBudcTjnMBcLveYqvbDqbE=,v9Pn0seyZOtp1Tb3UJ4NQBudcTjnMBcLveYqvbDqbE=,v9Pn0seyZOtp1Tb3UJ4NQBudcTjnMBcLveYqvbDqbE=,فلسطين,فلسطيني من اب فلسطيني الهويه ❤ اعشق فلسطين ❤😇...,NaN,772,1694,2018-11-14,...,absent,0.0,0.0,6.0,4.0,"['اردوغان', 'تركيا_غير_آمنه_للسفر', 'أبناء_أرد...",[],NaN,0,3059146444
173,1101857945808183297,KAg4N7MRzqPP6IwmFfclnWWgctJbvofGQmMI20mq8=,KAg4N7MRzqPP6IwmFfclnWWgctJbvofGQmMI20mq8=,KAg4N7MRzqPP6IwmFfclnWWgctJbvofGQmMI20mq8=,قطر,مساعد المظلومين وجسر للايادي البيضاء المحتاجة...,NaN,731,1627,2018-10-30,...,absent,0.0,0.0,0.0,0.0,"['الاردنية', 'السلطات_الارنيه']",[],NaN,0,1024439434471792640
314,940927282960416769,SIhFG6lNEyDStYbaIYDDeFVG31CKqxwHfJnCwz1iZ78=,SIhFG6lNEyDStYbaIYDDeFVG31CKqxwHfJnCwz1iZ78=,SIhFG6lNEyDStYbaIYDDeFVG31CKqxwHfJnCwz1iZ78=,NaN,NaN,NaN,31,38,2016-02-16,...,absent,0.0,0.0,0.0,0.0,[],[],NaN,0,368846546
316,1126454664877232129,jzw4x7jeG9ipPUL1osrm9SBFqjq6WhIMRU0BtLKRPFo=,jzw4x7jeG9ipPUL1osrm9SBFqjq6WhIMRU0BtLKRPFo=,jzw4x7jeG9ipPUL1osrm9SBFqjq6WhIMRU0BtLKRPFo=,Libya,🇱🇾🇱🇾🇱🇾ليبيا خط احمر,NaN,145,373,2015-09-29,...,absent,0.0,0.0,0.0,0.0,['فشلتونا_في_لاهاي'],[],NaN,0,470155874
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3723168,939467781254320128,vc3sZcwJWapy4g8Sywp1Tg5cDGd8IAfwn8G8hyY8pfY=,vc3sZcwJWapy4g8Sywp1Tg5cDGd8IAfwn8G8hyY8pfY=,vc3sZcwJWapy4g8Sywp1Tg5cDGd8IAfwn8G8hyY8pfY=,"Cairo, Egypt",NaN,NaN,62,132,2016-08-21,...,absent,0.0,0.0,0.0,0.0,[],[],NaN,17,754231566382104576
3723171,939467739139395584,vc3sZcwJWapy4g8Sywp1Tg5cDGd8IAfwn8G8hyY8pfY=,vc3sZcwJWapy4g8Sywp1Tg5cDGd8IAfwn8G8hyY8pfY=,vc3sZcwJWapy4g8Sywp1Tg5cDGd8IAfwn8G8hyY8pfY=,"Cairo, Egypt",NaN,NaN,62,132,2016-08-21,...,absent,0.0,0.0,0.0,0.0,[],[],NaN,17,754231566382104576
3723200,940860459011502080,iMmNBUOPjsAEaHySPWm6OP4AzIsGA0JA0GHwiz513pY=,iMmNBUOPjsAEaHySPWm6OP4AzIsGA0JA0GHwiz513pY=,iMmNBUOPjsAEaHySPWm6OP4AzIsGA0JA0GHwiz513pY=,United Arab Emirates,"Coffee, flowers, candles, makeup, fashion, lux...",NaN,49,133,2016-08-21,...,absent,0.0,0.0,0.0,0.0,[],[],NaN,17,2162368925
3938069,939467739139395584,vc3sZcwJWapy4g8Sywp1Tg5cDGd8IAfwn8G8hyY8pfY=,vc3sZcwJWapy4g8Sywp1Tg5cDGd8IAfwn8G8hyY8pfY=,vc3sZcwJWapy4g8Sywp1Tg5cDGd8IAfwn8G8hyY8pfY=,"Cairo, Egypt",NaN,NaN,62,132,2016-08-21,...,absent,0.0,0.0,0.0,0.0,[],[],NaN,18,465825590
3938098,940860459011502080,iMmNBUOPjsAEaHySPWm6OP4AzIsGA0JA0GHwiz513pY=,iMmNBUOPjsAEaHySPWm6OP4AzIsGA0JA0GHwiz513pY=,iMmNBUOPjsAEaHySPWm6OP4AzIsGA0JA0GHwiz513pY=,United Arab Emirates,"Coffee, flowers, candles, makeup, fashion, lux...",NaN,49,133,2016-08-21,...,absent,0.0,0.0,0.0,0.0,[],[],NaN,18,314475436

,tweetid,userid,user_display_name,user_screen_name,user_reported_location,user_profile_description,user_profile_url,follower_count,following_count,account_creation_date,...,longitude,quote_count,reply_count,like_count,retweet_count,hashtags,urls,poll_choices,variable,value
26,1130636632942620673,OnyzKfd1l2LdVEaqG8DxYkgk8xhckHnwsUKS6Wd6ZRw=,OnyzKfd1l2LdVEaqG8DxYkgk8xhckHnwsUKS6Wd6ZRw=,OnyzKfd1l2LdVEaqG8DxYkgk8xhckHnwsUKS6Wd6ZRw=,Libya,ليبي و افتخر 🇱🇾🇱🇾,NaN,149,430,2015-10-14,...,absent,0.0,0.0,0.0,0.0,"['قطر', 'الشعب_السوداني', 'اطردوا_مخابرات_قطر_...",[],NaN,0,2946753318
170,1119286214375419905,v9Pn0seyZOtp1Tb3UJ4NQBudcTjnMBcLveYqvbDqbE=,v9Pn0seyZOtp1Tb3UJ4NQBudcTjnMBcLveYqvbDqbE=,v9Pn0seyZOtp1Tb3UJ4NQBudcTjnMBcLveYqvbDqbE=,فلسطين,فلسطيني من اب فلسطيني الهويه ❤ اعشق فلسطين ❤😇...,NaN,772,1694,2018-11-14,...,absent,0.0,0.0,6.0,4.0,"['اردوغان', 'تركيا_غير_آمنه_للسفر', 'أبناء_أرد...",[],NaN,0,3059146444
173,1101857945808183297,KAg4N7MRzqPP6IwmFfclnWWgctJbvofGQmMI20mq8=,KAg4N7MRzqPP6IwmFfclnWWgctJbvofGQmMI20mq8=,KAg4N7MRzqPP6IwmFfclnWWgctJbvofGQmMI20mq8=,قطر,مساعد المظلومين وجسر للايادي البيضاء المحتاجة...,NaN,731,1627,2018-10-30,...,absent,0.0,0.0,0.0,0.0,"['الاردنية', 'السلطات_الارنيه']",[],NaN,0,1024439434471792640
314,940927282960416769,SIhFG6lNEyDStYbaIYDDeFVG31CKqxwHfJnCwz1iZ78=,SIhFG6lNEyDStYbaIYDDeFVG31CKqxwHfJnCwz1iZ78=,SIhFG6lNEyDStYbaIYDDeFVG31CKqxwHfJnCwz1iZ78=,NaN,NaN,NaN,31,38,2016-02-16,...,absent,0.0,0.0,0.0,0.0,[],[],NaN,0,368846546
316,1126454664877232129,jzw4x7jeG9ipPUL1osrm9SBFqjq6WhIMRU0BtLKRPFo=,jzw4x7jeG9ipPUL1osrm9SBFqjq6WhIMRU0BtLKRPFo=,jzw4x7jeG9ipPUL1osrm9SBFqjq6WhIMRU0BtLKRPFo=,Libya,🇱🇾🇱🇾🇱🇾ليبيا خط احمر,NaN,145,373,2015-09-29,...,absent,0.0,0.0,0.0,0.0,['فشلتونا_في_لاهاي'],[],NaN,0,470155874
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3723168,939467781254320128,vc3sZcwJWapy4g8Sywp1Tg5cDGd8IAfwn8G8hyY8pfY=,vc3sZcwJWapy4g8Sywp1Tg5cDGd8IAfwn8G8hyY8pfY=,vc3sZcwJWapy4g8Sywp1Tg5cDGd8IAfwn8G8hyY8pfY=,"Cairo, Egypt",NaN,NaN,62,132,2016-08-21,...,absent,0.0,0.0,0.0,0.0,[],[],NaN,17,754231566382104576
3723171,939467739139395584,vc3sZcwJWapy4g8Sywp1Tg5cDGd8IAfwn8G8hyY8pfY=,vc3sZcwJWapy4g8Sywp1Tg5cDGd8IAfwn8G8hyY8pfY=,vc3sZcwJWapy4g8Sywp1Tg5cDGd8IAfwn8G8hyY8pfY=,"Cairo, Egypt",NaN,NaN,62,132,2016-08-21,...,absent,0.0,0.0,0.0,0.0,[],[],NaN,17,754231566382104576
3723200,940860459011502080,iMmNBUOPjsAEaHySPWm6OP4AzIsGA0JA0GHwiz513pY=,iMmNBUOPjsAEaHySPWm6OP4AzIsGA0JA0GHwiz513pY=,iMmNBUOPjsAEaHySPWm6OP4AzIsGA0JA0GHwiz513pY=,United Arab Emirates,"Coffee, flowers, candles, makeup, fashion, lux...",NaN,49,133,2016-08-21,...,absent,0.0,0.0,0.0,0.0,[],[],NaN,17,2162368925
3938069,939467739139395584,vc3sZcwJWapy4g8Sywp1Tg5cDGd8IAfwn8G8hyY8pfY=,vc3sZcwJWapy4g8Sywp1Tg5cDGd8IAfwn8G8hyY8pfY=,vc3sZcwJWapy4g8Sywp1Tg5cDGd8IAfwn8G8hyY8pfY=,"Cairo, Egypt",NaN,NaN,62,132,2016-08-21,...,absent,0.0,0.0,0.0,0.0,[],[],NaN,18,465825590
3938098,940860459011502080,iMmNBUOPjsAEaHySPWm6OP4AzIsGA0JA0GHwiz513pY=,iMmNBUOPjsAEaHySPWm6OP4AzIsGA0JA0GHwiz513pY=,iMmNBUOPjsAEaHySPWm6OP4AzIsGA0JA0GHwiz513pY=,United Arab Emirates,"Coffee, flowers, candles, makeup, fashion, lux...",NaN,49,133,2016-08-21,...,absent,0.0,0.0,0.0,0.0,[],[],NaN,18,314475436

In [6]:
folder = 'venezuela'

In [5]:
for file in Path('COUNTRY_DATA/{}'.format(folder)).iterdir():
    print(file)

NameError: name 'folder' is not defined

In [ ]:
df = pd.DataFrame(
{'tweetid': pd.Series([], dtype='str'),
'userid': pd.Series([], dtype='str'),                  
'user_display_name': pd.Series([], dtype='str'),       
'user_screen_name': pd.Series([], dtype='str'),        
'user_reported_location': pd.Series([], dtype='str'),  
'user_profile_description': pd.Series([], dtype='str'),
'user_profile_url'  : pd.Series([], dtype='str'),    
'follower_count'   : pd.Series([], dtype='int'),     
'following_count'  : pd.Series([], dtype='int'),     
'account_creation_date' : pd.Series([], dtype='str'),
'account_language'  : pd.Series([], dtype='str'),   
'tweet_language'  : pd.Series([], dtype='str'),     
'tweet_text' : pd.Series([], dtype='str'),          
'tweet_time': pd.Series([], dtype='str'),           
'tweet_client_name'  : pd.Series([], dtype='str'),  
'in_reply_to_userid'  : pd.Series([], dtype='str'), 
'in_reply_to_tweetid' : pd.Series([], dtype='str'), 
'quoted_tweet_tweetid': pd.Series([], dtype='str'), 
'is_retweet' : pd.Series([], dtype='bool'),    
'retweet_userid' : pd.Series([], dtype='str'), 
'retweet_tweetid': pd.Series([], dtype='str'), 
'latitude'      : pd.Series([], dtype='str'),  
'longitude'   : pd.Series([], dtype='str'),    
'quote_count'  : pd.Series([], dtype='float'), 
'reply_count' : pd.Series([], dtype='float'),  
'like_count'  : pd.Series([], dtype='float'),  
'retweet_count' : pd.Series([], dtype='float'),
'hashtags' : pd.Series([], dtype='str'),   
'urls'   : pd.Series([], dtype='str'),     
'user_mentions' : pd.Series([], dtype='str'),
'poll_choices'    : pd.Series([], dtype='float')})


for file in Path(folder).iterdir():
    if file.name.endswith('.csv'):
        print('Reading {}'.format(file))
        with pd.read_csv('{}'.format(file),
                          chunksize=100000,
                          dtype= {'tweetid': str, 'userid': str,
                                  'in_reply_to_userid':str,'in_reply_to_tweetid': str,
                                  'quoted_tweet_tweetid': str,'retweet_userid': str,
                                  'retweet_tweetid': str, 'quote_count': float,
                                  'reply_count':float, 'like_count':float,'retweet_count':float,
                                  'tweet_time':object}) as reader:
            for chunk in reader:
                df = df.append(chunk)
                
print(df.info())

Reading venezuela/venezuela_201901_1_tweets_csv_hashed_2.csv
Reading venezuela/venezuela_201906_1_tweets_csv_hashed.csv
Reading venezuela/venezuela_linked_tweets_csv_hashed.csv
Reading venezuela/venezuela_201901_1_tweets_csv_hashed_3.csv
Reading venezuela/venezuela_201901_1_tweets_csv_hashed_1.csv

## Load Master Datasets

In [7]:
# Load all Tweets completed by IO actors
# only load first 1000000 for testing
masterTweets = pd.read_csv('_masterTweetList_2021-03.csv', nrows=1000000)
masterTweets["m_userid"]= masterTweets["m_userid"].astype(str) 
masterTweets["m_tweetid"]= masterTweets["m_tweetid"].astype(str) 

"""CONFIRM CSV DATE"""
masterUIDs = pd.read_csv('_masterUIDs_2021-03.csv')
masterUIDs = masterUIDs[masterUIDs['id']!='userid']
masterUIDs.id = masterUIDs.id.apply(str)

## Edges Test

In [8]:
df = pd.read_pickle('_Parsed/armenia_parsed_1.pkl')
df.tweetid = df.tweetid.apply(str)
df.userid = df.userid.apply(str)
df.reply_user_id = df.reply_user_id.apply(str)
df.retweet_user_id = df.retweet_user_id.apply(str)


####### RETWEET Actors #######
print('working retweets')
dfRT = df[df['is_retweet'] != 'false'] # removes all Tweets that are not RTs
dfRT = dfRT[dfRT['is_retweet'] != 'FALSE']
dfRT2 = df[df['retweet_user_id'] != ''] # removes all Tweets that are not retweets
dfRT3 = df[df['retweet_tweet_id'] != ''] # removes all Tweets that are not retweets
dfRT = pd.concat([dfRT, dfRT2, dfRT3])
dfRT = dfRT.drop_duplicates(subset='tweetid', keep='first')
dfRT['retweet_tweet_id'] = dfRT.retweet_tweet_id.apply(str)
dfRT = pd.merge(dfRT,masterTweets,left_on='retweet_tweet_id',right_on='m_tweetid',how= 'left')
# Merge will help identify if any parent RT is made by an IO actor in collection..based off TweetID. 

dfRT_edges1 = dfRT.copy()
dfRT_edges1 = dfRT_edges1[~dfRT_edges1['m_userid'].isnull()]
dfRT_edges1 = dfRT_edges1[['tweetid', 'userid', 'm_userid', 'tweet_time']]
dfRT_edges1 = dfRT_edges1.drop_duplicates()


dfRT['retweet_user_id'] = dfRT.retweet_user_id.apply(str)
dfRT = pd.merge(dfRT,masterUIDs,left_on='retweet_user_id',right_on='id',how= 'left')
# Merge will help identify if any parent RT is made by an IO actor in collection..based off UserID. 

dfRT_edges2 = dfRT.copy()
dfRT_edges2 = dfRT_edges2[~dfRT_edges2['id'].isnull()]
dfRT_edges2 = dfRT_edges2[['tweetid', 'userid', 'id', 'tweet_time']]
dfRT_edges2 = dfRT_edges2.drop_duplicates()

dfRT_edges1.columns = ['tweetid', 'userid', 'parentID', 'tweet_time']
dfRT_edges2.columns = ['tweetid', 'userid', 'parentID', 'tweet_time']
RT_edges = pd.concat([dfRT_edges1, dfRT_edges2])
RT_edges = RT_edges.drop_duplicates()
RT_edges['edge_type'] = 'retweet'


####### REPLY Actors #######
print('working replies')
dfRply = df[df['reply_user_id'] != ''] # removes all Tweets that are not replies
dfRply2 = df[df['reply_tweet_id'] != '']
dfRply = pd.concat([dfRply, dfRply2])
dfRply = dfRply.drop_duplicates(subset='tweetid', keep='first')

dfRply['reply_tweet_id'] = dfRply.reply_tweet_id.apply(str)
dfRply['reply_user_id'] = dfRply.reply_user_id.apply(str)
dfRply = pd.merge(dfRply, masterTweets, left_on='reply_tweet_id', right_on='m_tweetid', how='left')
dfRply = pd.merge(dfRply, masterUIDs, left_on='reply_user_id', right_on='id', how='left')
dfRply

RP_edges1 = dfRply[~dfRply['id'].isnull()]
RP_edges1 = RP_edges1[['tweetid', 'userid', 'id', 'tweet_time']]
RP_edges1.columns = ['tweetid', 'userid', 'parentID', 'tweet_time']
RP_edges2 = dfRply[~dfRply['m_userid'].isnull()]
RP_edges2 = RP_edges2[['tweetid', 'userid', 'm_userid', 'tweet_time']]
RP_edges2.columns = ['tweetid', 'userid', 'parentID', 'tweet_time']
RP_edges = pd.concat([RP_edges1, RP_edges2])
RP_edges = RP_edges.drop_duplicates()
RP_edges['edge_type'] = 'reply'




####### QUOTE Actors #######
print('working quotes')
dfQT = df[df['quote_tweet_id'] != ''] # removes all Tweets that are not quotes
# print('Len of dfQT: {}\n'.format(len(dfQT)))
dfQT['quote_tweet_id'] = dfQT.quote_tweet_id.apply(str)

dfQT = pd.merge(dfQT,masterTweets,left_on='quote_tweet_id',right_on='m_tweetid',how= 'inner')
dfQT = dfQT.drop_duplicates()
dfQT = dfQT[~dfQT['m_userid'].isnull()]
QT_edges = dfQT[['tweetid', 'userid', 'm_userid', 'tweet_time']]
QT_edges.columns = ['tweetid', 'userid', 'parentID', 'tweet_time']
QT_edges['edge_type'] = 'quote'


####### MENTIONED Actors #######
print('working Mentions')
df['mentions'] = df['mentions'].str.replace(']', '')
df['mentions'] = df['mentions'].str.replace('[', '')
df['mentions'] = df['mentions'].str.replace(' ', '')
df['mentions'] = df['mentions'].str.replace('\'', '')
df2 = df.copy()
df2 = df2.join(df2.pop('mentions').str.split(',',expand=True))
df2.set_index(['tweetid','userid', 'accountDate', 'account_lang', 'tweet_lang',
              'text', 'tweet_time', 'tweetClient', 'reply_user_id', 'reply_tweet_id',
              'quote_tweet_id', 'is_retweet', 'retweet_user_id', 'retweet_tweet_id',
              'quote_count', 'reply_count', 'like_count', 'retweet_count', 'hashtags',
              'urls']).stack().reset_index(level=[0,1],name='mention')



df_melt = df2.melt(id_vars =['tweetid','userid','accountDate',
                            'account_lang','tweet_lang','text',
                            'tweet_time','tweetClient','reply_user_id',
                            'reply_tweet_id','quote_tweet_id','is_retweet',
                            'retweet_user_id','retweet_tweet_id','quote_count',
                             'reply_count', 'like_count', 'retweet_count', 'hashtags','urls']).dropna()

df_melt = df_melt.rename(columns={'value': 'id'})
df_melt.id = df_melt.id.apply(str)


dfMT = pd.merge(df_melt, masterUIDs, on=['id'], how='left')

MT_edges = dfMT[~dfMT['country'].isnull()]
MT_edges = MT_edges.drop_duplicates()
MT_edges = MT_edges[['tweetid', 'userid', 'id', 'tweet_time']]
MT_edges.columns = ['tweetid', 'userid', 'parentID', 'tweet_time']
MT_edges['edge_type'] = 'mention'

print('Merging all edges')
IO_edges = pd.concat([RT_edges, RP_edges, QT_edges, MT_edges])
IO_edges = IO_edges.drop_duplicates()
IO_edges.to_csv('_Edges/_{}_IO_edges_{}.csv'.format('armenia', 1), index = False)

NameError: name 'df' is not defined

In [15]:
import os
import pandas as pd

country_list = ['armenia', 'bangladesh', 'catalonia', 'ecuador', 'china', 'cuba', 'egypt', 'honduras', 'indonesia', 'iran',
        'russia', 'saudi_arabia', 'serbia', 'spain', 'thailand', 'turkey', 'uae', 'uae_egypt', 'venezuela']


IO_actors_master = pd.DataFrame(columns=['userid', 'country'])

for country in country_list: 
    print(country)
    matching_files = [f for f in os.listdir('./_IOactors') if country in f]
    print(matching_files)
    for f in matching_files:
        df = pd.read_csv('_IOactors/{}'.format(f))
        df['country'] = country
        df['userid'] = df['userid'].apply(str)
        print(df)
        IO_actors_master = IO_actors_master.append(df)
        print(len(IO_actors_master))

# IO_actors_master.to_csv('_masterIOactors.csv', index=False)

armenia
['_armenia_IOactors_1.csv']
                                          userid  country
0    9tv1gRACFz8IPY6lCkXCgaXEJh1Ol2Fk78bhuCGhyA=  armenia
1    vrJSje34LOxmhLf7y0QqVdtulQZBm6QfOtxswidhrs=  armenia
2      2rg8fiE11JB8Bh69A6aJWeRSBPcGTAmK8wnpFpH0=  armenia
3    Tf0FY7EDYEUVzBsJNSLmYJ0nBSU4Z38qsQxp48GpxA=  armenia
4    lLmWQV16uj+BD2rwXOahQYX2GdGcAMsDlIFzIidYk4=  armenia
5     uqU5V82g6lpOgJjvDGLIA4LEFT2wGmque+vYhRUTk=  armenia
6     OVC8cA0LTalwGqP2ooefLPsdlJmbB5wF+hpKZuRp0=  armenia
7     Rgex8nPtn9Y4bvWf9RMb8yI2GGWP65yTXb+9ZygHU=  armenia
8     1L0qn8rgg4bi6tCYH934gRpAQG59vTUg9kPubBzxM=  armenia
9   rOr0az+xkI49HIn0VwU6R1Som+obkg6E84AqY5hnoTo=  armenia
10    p8PbTRSSnu3Re1jI+c33x2TdFAKbqe6P5ZSQGmlbQ=  armenia
11    Dw3BUtxw5YA0q9KN9iSzs8OfJBlwR6yd1abnKmfds=  armenia
12  cZOjRuZC9y0Gh52T2gucxx1agq70VE2cSus9VWC1nUc=  armenia
13   RjBg+chC8o0DUgVLzMEtJKK1MrsHCwbRSJs1MSbJWU=  armenia
14   Nc3kQgzsNAqdsI8HIZvLUBqBrC2R2GmZsx0KZ81YgE=  armenia
15   eo0xpq4n+8U5Uy2FZlrcxtBEd0gldAZyDPDT+7D+wY=  armenia
16     e7MA8928eiTvHTGw7lNORtEVx85xr8YkmbJuYv80=  armenia
17   3bc6BmmosKy9g+hwhMnLbHJWbe4pYksRUKf+aM50go=  armenia
18   J+DqVRUnxy1xebmfFWlFz6O2jaweNQipELiIwGmC78=  armenia
19  1Pqyt2W75POPX+6zd9UdZL89ALBtPPELN4NPrly0nag=  armenia
20   46eJLsV6+iDw1rVv36i9NONigsfqfTfQ9EBzXr901c=  armenia
21  hIwvijBQgtzTif1aiKe2oyhLTLj780vfUz8pJfXDEYI=  armenia
22   GirKucHHVYqwkhuyAv8ypYqFiJEerIARdbMGI8Szqs=  armenia
23  udD+2utCbaNF44kJOjT5lLCtp8lsFTEnTeIdeu7LUHc=  armenia
24   9I2UVCTjRhYZvhxhkCC13U0HAU1ZAHDZbX1kpc3cVc=  armenia
25
bangladesh
['_bangladesh_IOactors.csv', '_bangladesh_IOactors_1.csv']
                                         userid     country
0    UOYzWkr60fJQXg134s861VR6yVN8ECzm9Onrnvu5s=  bangladesh
1     sH4nmm9uSa2mNpr17PfNWQnfcicVI5kunx3kd4q4=  bangladesh
2  0OvJRirnL32w7blCoMRthk30yPlXapfIPFac4Eyje0k=  bangladesh
3   QGdKV23i9r+ocu2cySQC8J8O0BJmxQLM8n4xB6RQg8=  bangladesh
4  8hYvkOW7QTWoKSZvoR1Ru5nzEMBVFVskc7xepyhQJBo=  bangladesh
5  5yP0DlSBuPEQJIOdniuznIo1Roucbu6jVHZNUnHcei0=  bangladesh
31
                                         userid     country
0    UOYzWkr60fJQXg134s861VR6yVN8ECzm9Onrnvu5s=  bangladesh
1     sH4nmm9uSa2mNpr17PfNWQnfcicVI5kunx3kd4q4=  bangladesh
2  0OvJRirnL32w7blCoMRthk30yPlXapfIPFac4Eyje0k=  bangladesh
3   QGdKV23i9r+ocu2cySQC8J8O0BJmxQLM8n4xB6RQg8=  bangladesh
4  8hYvkOW7QTWoKSZvoR1Ru5nzEMBVFVskc7xepyhQJBo=  bangladesh
5  5yP0DlSBuPEQJIOdniuznIo1Roucbu6jVHZNUnHcei0=  bangladesh
37
catalonia
['_catalonia_IOactors.csv', '_catalonia_IOactors_1.csv']
                                          userid    country
0     PU2wqnANI5yVpnwhdNC7NXIWtmAK2wMz9UYU1S9hE=  catalonia
1   KP5YMWpjuwsjsDERWSgWmv6P9Mo52dSkR1VX9tOg1xo=  catalonia
2   zcjq53ah8JMLh5XvL3sNbtReAefJI5gCCPCxSLmIgpU=  catalonia
3   WmuGrcKvlItmfLcYo8JqFvqcwfJ7hn0jvHrAFZHpdBo=  catalonia
4    MXRyIffolYVIxjHoo4L8kZrhgwV0Q5gTL3t4EYo1wU=  catalonia
5    gD0tW1UsTJ84HRIgqhF8kPd1A8TnEAwgvHMlBx5cVQ=  catalonia
6    1cEGAfP+VQNssv8cGnPvqrEXcgJg2HLZPU36aHplSE=  catalonia
7   D5u03QBMAjjm5+srZTeo18pvQh945c+45ZFxkTl4d7Y=  catalonia
8                             738418101964951552  catalonia
9   dn7ih4cOZgZnV4GQIby7Jx777VbMO78iMv8ZDghRP7g=  catalonia
10   BL3MWry3mDc5fsUPQOzEoln7zrpLVpHfc6akUcg7eY=  catalonia
11    Ev0VHfwnqzm5CVKlM3lPQACUsdRrgfPKFn9rhFz3E=  catalonia
12  Qz+iYFIZhuqvlhnz4kAqR0XNEOoh2nuLocTy4S6tEwM=  catalonia
13  KGAI0fEBvCGsNyUXU8OSAtZPzu8MFzhtPcvUcEE9Dk8=  catalonia
14  PY2C4qh5lyaxXx4iMkzdEJwtDhgQWed0Fh3pi2siO5Q=  catalonia
15  OgEr3CckYbSISQ50z5cxoMZmpHfTqfWkGS+QIEOxvrk=  catalonia
16  n5GnY2rQGIj+JhyiHtdRmkwTRJSwhDN9By75qEwlglw=  catalonia
17   Dbx6LUGQiFQC5t3Q2kUq25GJy7YZLEGAapJlKxsaG4=  catalonia
18  +MDKcRIqPyw7X+QpITKl8SYQGgHhhKx5WFfeqqtT9E4=  catalonia
19   zUjiJFB69qMY+RWAZSEwz9VBgvbseWYw37tKvdhgAM=  catalonia
20    9MTuIXlMP8IMY495D+PllDmUurGmeT+E494x1m7Ls=  catalonia
21  mNwaZeg9PvWpQhiJGLoVG83MZDkHNOquylRnrQ6KDx4=  catalonia
22  Fa93qlpuY4fS8cmCde0owlwmhgEpvvc7tNNPgbQJHZA=  catalonia
23   aeIn1Nuih56vVUsV4agSV6U25W2hJkJui9yWwx3Q30=  catalonia
24  nnGzJGcAm2FofS5jNOQa9b9bBP0BIizhg3DjDNHN5SY=  catalonia
25  5gA4hZvZdRLfPSr7WIuGvcyMymZb0O12rgByz8jO3EE=  catalonia
26   U07+ovhpwHvX886BsOrh+lgBxFc1gVDHbWiX3q3P5Q=  catalonia
27  0TWCMWEH6OsTPGHH8K9LWhAv26gyf3fOKFSXvvtv57U=  catalonia
28    TJqkhdNAE1foBuiPILYdC0UqJR30hjitt7ofkBZOQ=  catalonia
29   n4MpmhygUrdAwix1BqRcNPMsz1XM93xF9WGgJngqz4=  catalonia
30  kMRTBFD+GojvCgtvSsVfjpkcpBnr6cD6kdxRYpKIth0=  catalonia
31   R++Q6XPQyClA9E3Rx8EU9lsPr83h+QgFCgYFyCsTTo=  catalonia
32  D3SRw1xHubzK8dGbxOXzjMYep73U5D1XbTalvHMhkqc=  catalonia
33   YrT7Ex3niJbdGprZ2Sv6HZEE6L42ZZp4wy7P0NPXRc=  catalonia
34  XEWt0hkjqgssZK5h4RTVhvZmYiaNYUJCPGvXL8Lgygw=  catalonia
35  +U90wpIvhEI+To2IZHv5MxW8438+NJFVftZNib3v18I=  catalonia
36   oreTBxWxFWOjmecN2SgwfFOWkLkl4tgICEkeLDyVw8=  catalonia
37  Au48dZ+Jhy5Z5bghIpe8ZU8gN4yQrIIFZpI1i8WWxHI=  catalonia
38  kxQjWzWi27zAb8UXb2NjoFx69UpFfuO6qdVkvdwH6Fs=  catalonia
76
                                          userid    country
0     PU2wqnANI5yVpnwhdNC7NXIWtmAK2wMz9UYU1S9hE=  catalonia
1   KP5YMWpjuwsjsDERWSgWmv6P9Mo52dSkR1VX9tOg1xo=  catalonia
2   zcjq53ah8JMLh5XvL3sNbtReAefJI5gCCPCxSLmIgpU=  catalonia
3   WmuGrcKvlItmfLcYo8JqFvqcwfJ7hn0jvHrAFZHpdBo=  catalonia
4    MXRyIffolYVIxjHoo4L8kZrhgwV0Q5gTL3t4EYo1wU=  catalonia
5    gD0tW1UsTJ84HRIgqhF8kPd1A8TnEAwgvHMlBx5cVQ=  catalonia
6    1cEGAfP+VQNssv8cGnPvqrEXcgJg2HLZPU36aHplSE=  catalonia
7   D5u03QBMAjjm5+srZTeo18pvQh945c+45ZFxkTl4d7Y=  catalonia
8                             738418101964951552  catalonia
9   dn7ih4cOZgZnV4GQIby7Jx777VbMO78iMv8ZDghRP7g=  catalonia
10   BL3MWry3mDc5fsUPQOzEoln7zrpLVpHfc6akUcg7eY=  catalonia
11    Ev0VHfwnqzm5CVKlM3lPQACUsdRrgfPKFn9rhFz3E=  catalonia
12  Qz+iYFIZhuqvlhnz4kAqR0XNEOoh2nuLocTy4S6tEwM=  catalonia
13  KGAI0fEBvCGsNyUXU8OSAtZPzu8MFzhtPcvUcEE9Dk8=  catalonia
14  PY2C4qh5lyaxXx4iMkzdEJwtDhgQWed0Fh3pi2siO5Q=  catalonia
15  OgEr3CckYbSISQ50z5cxoMZmpHfTqfWkGS+QIEOxvrk=  catalonia
16  n5GnY2rQGIj+JhyiHtdRmkwTRJSwhDN9By75qEwlglw=  catalonia
17   Dbx6LUGQiFQC5t3Q2kUq25GJy7YZLEGAapJlKxsaG4=  catalonia
18  +MDKcRIqPyw7X+QpITKl8SYQGgHhhKx5WFfeqqtT9E4=  catalonia
19   zUjiJFB69qMY+RWAZSEwz9VBgvbseWYw37tKvdhgAM=  catalonia
20    9MTuIXlMP8IMY495D+PllDmUurGmeT+E494x1m7Ls=  catalonia
21  mNwaZeg9PvWpQhiJGLoVG83MZDkHNOquylRnrQ6KDx4=  catalonia
22  Fa93qlpuY4fS8cmCde0owlwmhgEpvvc7tNNPgbQJHZA=  catalonia
23   aeIn1Nuih56vVUsV4agSV6U25W2hJkJui9yWwx3Q30=  catalonia
24  nnGzJGcAm2FofS5jNOQa9b9bBP0BIizhg3DjDNHN5SY=  catalonia
25  5gA4hZvZdRLfPSr7WIuGvcyMymZb0O12rgByz8jO3EE=  catalonia
26   U07+ovhpwHvX886BsOrh+lgBxFc1gVDHbWiX3q3P5Q=  catalonia
27  0TWCMWEH6OsTPGHH8K9LWhAv26gyf3fOKFSXvvtv57U=  catalonia
28    TJqkhdNAE1foBuiPILYdC0UqJR30hjitt7ofkBZOQ=  catalonia
29   n4MpmhygUrdAwix1BqRcNPMsz1XM93xF9WGgJngqz4=  catalonia
30  kMRTBFD+GojvCgtvSsVfjpkcpBnr6cD6kdxRYpKIth0=  catalonia
31   R++Q6XPQyClA9E3Rx8EU9lsPr83h+QgFCgYFyCsTTo=  catalonia
32  D3SRw1xHubzK8dGbxOXzjMYep73U5D1XbTalvHMhkqc=  catalonia
33   YrT7Ex3niJbdGprZ2Sv6HZEE6L42ZZp4wy7P0NPXRc=  catalonia
34  XEWt0hkjqgssZK5h4RTVhvZmYiaNYUJCPGvXL8Lgygw=  catalonia
35  +U90wpIvhEI+To2IZHv5MxW8438+NJFVftZNib3v18I=  catalonia
36   oreTBxWxFWOjmecN2SgwfFOWkLkl4tgICEkeLDyVw8=  catalonia
37  Au48dZ+Jhy5Z5bghIpe8ZU8gN4yQrIIFZpI1i8WWxHI=  catalonia
38  kxQjWzWi27zAb8UXb2NjoFx69UpFfuO6qdVkvdwH6Fs=  catalonia
115
ecuador
['_ecuador_IOactors_1.csv', '_ecuador_IOactors.csv']
                                           userid  country
0    ukVRK3bdc+PulA7j2BFeIbKLc0oapD9rIbs+GfNHNmM=  ecuador
1    CXhZKh19mZ+dpt32TAH3kUDdKe8jTrpXURpDnFhYZcI=  ecuador
2     T+29kB4weuZQzIJVW5PIwYo0NhMCV6B18uBxfJ974Y=  ecuador
3    iSZjvrh0O8JLqwgsz8daiPC1H7AEfILNDk6ifURiF8U=  ecuador
4    NgUDrvK6u3tyiVkxFZ6bFkApz1e32pPhTP5mL+bFcac=  ecuador
..                                            ...      ...
390  bDrk51ulMNffYo2QBkgx69kKGXLtmsPDB0OtuBtpMsY=  ecuador
391   iNePL5PVjfzU+SapgfmgitmVoUwIjcf9ugOxm9zHnI=  ecuador
392   ki0mMdynIVQCboGIvK8soYK26DmcyfDr4g7hdE5SpI=  ecuador
393  YTWUP8My2gBsCdtwPc1SXNAumFkAOZzVEksuQrDzFPM=  ecuador
394  8SLgQyViLWYqR7amsF2Nq0aG1ouQrhCqDVJl0S8bxkM=  ecuador

[395 rows x 2 columns]
510
                                           userid  country
0    ukVRK3bdc+PulA7j2BFeIbKLc0oapD9rIbs+GfNHNmM=  ecuador
1    CXhZKh19mZ+dpt32TAH3kUDdKe8jTrpXURpDnFhYZcI=  ecuador
2     T+29kB4weuZQzIJVW5PIwYo0NhMCV6B18uBxfJ974Y=  ecuador
3    iSZjvrh0O8JLqwgsz8daiPC1H7AEfILNDk6ifURiF8U=  ecuador
4    NgUDrvK6u3tyiVkxFZ6bFkApz1e32pPhTP5mL+bFcac=  ecuador
..                                            ...      ...
389  bDrk51ulMNffYo2QBkgx69kKGXLtmsPDB0OtuBtpMsY=  ecuador
390   iNePL5PVjfzU+SapgfmgitmVoUwIjcf9ugOxm9zHnI=  ecuador
391   ki0mMdynIVQCboGIvK8soYK26DmcyfDr4g7hdE5SpI=  ecuador
392  YTWUP8My2gBsCdtwPc1SXNAumFkAOZzVEksuQrDzFPM=  ecuador
393  8SLgQyViLWYqR7amsF2Nq0aG1ouQrhCqDVJl0S8bxkM=  ecuador

[394 rows x 2 columns]
904
china
['_china_IOactors_6.csv', '_china_IOactors.csv', '_china_IOactors_2.csv', '_china_IOactors_7.csv', '_china_IOactors_1.csv', '_china_IOactors_5.csv', '_china_IOactors_3.csv']
                userid country
0   859747183985270784   china
1           1528368942   china
2           1904761490   china
3           2194890905   china
4           1261250516   china
..                 ...     ...
86          4727891851   china
87          2855845884   china
88          2871129087   china
89          2724327834   china
90  806001010959216644   china

[91 rows x 2 columns]
995
                                             userid country
0                                775462690210787329   china
1                                944503073648476160   china
2                                        4517518895   china
3        ioZ2kcf52Ilga8Ja9eLMeEsgN4wGkGWhSV9VnmjFI=   china
4                               1031398757407940608   china
...                                             ...     ...
24370     cGJkrJQP9K+Ga5bqfcWapWh5+yG6LHeocwTDLmBk=   china
24371  6a+b85kxMhkXZHN1oGnlgU1VfgeNU5+54GkqSfM+wOk=   china
24372   xz4vDD2m71uvSabJZ9n9QXiVm2SnVx3s592SVoocKI=   china
24373   DYKYS86gRj09e4pg4ibDFauSnNrR3JRrUOhaVjAzp4=   china
24374                            745790133274804225   china

[24375 rows x 2 columns]
25370
                                             userid country
0                                          64465129   china
1                               1038660680784601088   china
2                               1047137659888386049   china
3                               1130699379499708417   china
4                               1042646347751411713   china
...                                             ...     ...
23560  RmcP8e2buWiKHnXqjXY2POxpWjrYroFDeFHSgWwf+Z4=   china
23561     cGJkrJQP9K+Ga5bqfcWapWh5+yG6LHeocwTDLmBk=   china
23562  6a+b85kxMhkXZHN1oGnlgU1VfgeNU5+54GkqSfM+wOk=   china
23563   xz4vDD2m71uvSabJZ9n9QXiVm2SnVx3s592SVoocKI=   china
23564   DYKYS86gRj09e4pg4ibDFauSnNrR3JRrUOhaVjAzp4=   china

[23565 rows x 2 columns]
48935
                                           userid country
0    Do0s7EkwSQ0rSJP7HeWjO1tn7dHvKnc1SBRYfT9PwXI=   china
1    eCY9KQ5z16BIupEGnkmHD4uc56nNKt+9++3IB42I+D8=   china
2                              747309343624704000   china
3    LQV+YJdIxi7pAp7BI7eISH4TYv5hv0d8U5k4DwD0wLs=   china
4     uSeViCRXvlKQSSTLmiXtHlH9jQbLI+diQQ6vZeoylk=   china
..                                            ...     ...
389    yK2YrSMkSU1HY1xAp8v+MYkhQJr957mizOJwCkTe8=   china
390                            982902029029797888   china
391                                     533748701   china
392                            745790133274804225   china
393                                    2401552109   china

[394 rows x 2 columns]
49329
                                          userid country
0                             775462690210787329   china
1                             944503073648476160   china
2                                     4517518895   china
3     ioZ2kcf52Ilga8Ja9eLMeEsgN4wGkGWhSV9VnmjFI=   china
4                            1031398757407940608   china
...                                          ...     ...
4245                          730618449081208832   china
4246                                  2595648476   china
4247                                  1104766315   china
4248                          908334203338502144   china
4249                         1077903793616908288   china

[4250 rows x 2 columns]
53579
                                          userid country
0                             925190562512224256   china
1                                     4547573535   china
2                            1068572196904128513   china
3    dqssMk0+QAXhY+TdoTLDY2rw8StxqjzVMInao2Lyag=   china
4                                     2996885875   china
..                                           ...     ...
197                           806001010959216644   china
198                           730618449081208832   china
199                                   4727891851   china
200                           859747183985270784   china
201                                   1100733727   china

[202 rows x 2 columns]
53781
        userid country
0   1944006122   china
1   1104766315   china
2   1331312911   china
3   1588282730   china
4   1261148118   china
..         ...     ...
69  2871129087   china
70  1577127739   china
71  2855845884   china
72  1138742714   china
73   704679373   china

[74 rows x 2 columns]
53855
cuba
['_cuba_IOactors.csv', '_cuba_IOactors_1.csv']
                                           userid country
0                                       846257983    cuba
1    eX3mhgCPRTdwaWe0Gkdk4gFJuSBct+TEzARBB7zqM5I=    cuba
2                             1100203677271363589    cuba
3     OLgiNaYV3jQ2vNc5TcwMo3Zixoyegx+yNcosbOsE6A=    cuba
4       dHsddsDNPqenKvn0NLFpIi6W+R2zEml40CB6sJQo=    cuba
..                                            ...     ...
536                           1019185454296567808    cuba
537                                    2387651936    cuba
538                                      27025251    cuba
539  lWGX4M2jkz0ze4Khx0z2dUZz7gaZ9ZrqK27DKI98v50=    cuba
540  KyOwKaFiaEanhK+ZRDR2udlLrd2jdyLVNOhjn4Jbxgw=    cuba

[541 rows x 2 columns]
54396
                                           userid country
0                                       846257983    cuba
1    eX3mhgCPRTdwaWe0Gkdk4gFJuSBct+TEzARBB7zqM5I=    cuba
2                             1100203677271363589    cuba
3     OLgiNaYV3jQ2vNc5TcwMo3Zixoyegx+yNcosbOsE6A=    cuba
4       dHsddsDNPqenKvn0NLFpIi6W+R2zEml40CB6sJQo=    cuba
..                                            ...     ...
537                           1019185454296567808    cuba
538                                    2387651936    cuba
539                                      27025251    cuba
540  lWGX4M2jkz0ze4Khx0z2dUZz7gaZ9ZrqK27DKI98v50=    cuba
541  KyOwKaFiaEanhK+ZRDR2udlLrd2jdyLVNOhjn4Jbxgw=    cuba

[542 rows x 2 columns]
54938
egypt
['_egypt_IOactors.csv', '_egypt_IOactors_1.csv', '_uae_egypt_IOactors.csv', '_uae_egypt_IOactors_1.csv']
                                            userid country
0     azuf3RmznMPoQqkpW8WMgWA9SHn1WskzUVEvzeX8+Ac=   egypt
1                                       1259387862   egypt
2                                       1664006540   egypt
3       x0lhpweBqMrGlQhf5RMPAYbw8l7YqvDUv92OtMt7I=   egypt
4     wZ4wth7jZIqhDqnBlBtN0BPsbgJ9IcqcTCLWKVqzG7U=   egypt
...                                            ...     ...
2070  nQyO5JvLC4hmRSuHKJB4EcKDn18u0SsdJ7UeTkSBlOg=   egypt
2071   OCABHMkLGzEZHCAD5zTCyo7QWHfDjosLRYRGiGROvk=   egypt
2072     debcOku3P1XoicRxLvKCDyDzcOhK7Tz+rv1Q3N3c=   egypt
2073   bBFKpaln+fYGFocrpz7puPVzsvS0vvYmUYmuphMTwY=   egypt
2074   QtZXsznqcRo2uGG8PVpqYUndQaW4udvilm7I5rt+sw=   egypt

[2075 rows x 2 columns]
57013
                                            userid country
0     azuf3RmznMPoQqkpW8WMgWA9SHn1WskzUVEvzeX8+Ac=   egypt
1                                       1259387862   egypt
2                                       1664006540   egypt
3       x0lhpweBqMrGlQhf5RMPAYbw8l7YqvDUv92OtMt7I=   egypt
4     wZ4wth7jZIqhDqnBlBtN0BPsbgJ9IcqcTCLWKVqzG7U=   egypt
...                                            ...     ...
2071  nQyO5JvLC4hmRSuHKJB4EcKDn18u0SsdJ7UeTkSBlOg=   egypt
2072   OCABHMkLGzEZHCAD5zTCyo7QWHfDjosLRYRGiGROvk=   egypt
2073     debcOku3P1XoicRxLvKCDyDzcOhK7Tz+rv1Q3N3c=   egypt
2074   bBFKpaln+fYGFocrpz7puPVzsvS0vvYmUYmuphMTwY=   egypt
2075   QtZXsznqcRo2uGG8PVpqYUndQaW4udvilm7I5rt+sw=   egypt

[2076 rows x 2 columns]
59089
                                           userid country
0                              869180784728518656   egypt
1      EEstHwOwHRNWIefhWQhr1jlKZoxl+hpb51++13+E4=   egypt
2     sAMCJGsRrL1AuWEMMJ183Wd1BlP0GKxQft7RCIVQio=   egypt
3     zSQFG4VqDBoxFDzNteoCcy3JuDNfWjllIDMHQkGBzg=   egypt
4                              981925161271250945   egypt
..                                            ...     ...
220                                    1139364402   egypt
221                                     989808386   egypt
222                                    4558713094   egypt
223    hd92rmFmAkVjMKMDv807KZOTx79KBuXAWXpl1daL8=   egypt
224  3f3uWoPaOVxzGz9bqFDO8FLTePIIduMObqNs4oN6eFs=   egypt

[225 rows x 2 columns]
59314
                                           userid country
0                              869180784728518656   egypt
1      EEstHwOwHRNWIefhWQhr1jlKZoxl+hpb51++13+E4=   egypt
2     sAMCJGsRrL1AuWEMMJ183Wd1BlP0GKxQft7RCIVQio=   egypt
3     zSQFG4VqDBoxFDzNteoCcy3JuDNfWjllIDMHQkGBzg=   egypt
4                              981925161271250945   egypt
..                                            ...     ...
220                                    1139364402   egypt
221                                     989808386   egypt
222                                    4558713094   egypt
223    hd92rmFmAkVjMKMDv807KZOTx79KBuXAWXpl1daL8=   egypt
224  3f3uWoPaOVxzGz9bqFDO8FLTePIIduMObqNs4oN6eFs=   egypt

[225 rows x 2 columns]
59539
honduras
['_honduras_IOactors_1.csv', '_honduras_IOactors.csv']
                                            userid   country
0        j6dnx7sZxasXiEqVLxcs66tRc49b4rSanKiSGZ1M=  honduras
1      ZPzjLypEC1sLADwjmYu4tTxmQ7jCs3nnPaV73HoB7w=  honduras
2     TMhbI0e04FuqA5NwhPNWKTrUkErldwy3SrZwkcSBY8M=  honduras
3     dtcvL99Zaimii305A2DtDW3ijyjPZgcUoasHkCajw54=  honduras
4     RWoRVc1u3NHzkpdN9q3OoLC9qj1ZbeO5bibeSCNlty4=  honduras
...                                            ...       ...
1378  NCHu7bbR5E+TwN6aruNFoKeH93HknU6sz9Si9QUnDnk=  honduras
1379  wBhA14paIj5UVs00vOzfGjQX5QqHX44ETRwGV5xMzmc=  honduras
1380   H586CJp3SN2C8H3xlubuNayoooZK5V3Yy3ovuwXLP0=  honduras
1381   Maj5kGMug0RDaWpUPMJ7R57ZFCopUK4LSV4t+tgzCg=  honduras
1382   qkAFvx66BCyc42+BZyJsMlzlbwzZcxzUfczZrE0K08=  honduras

[1383 rows x 2 columns]
60922

                                            userid   country
0        j6dnx7sZxasXiEqVLxcs66tRc49b4rSanKiSGZ1M=  honduras
1      ZPzjLypEC1sLADwjmYu4tTxmQ7jCs3nnPaV73HoB7w=  honduras
2     TMhbI0e04FuqA5NwhPNWKTrUkErldwy3SrZwkcSBY8M=  honduras
3     dtcvL99Zaimii305A2DtDW3ijyjPZgcUoasHkCajw54=  honduras
4     RWoRVc1u3NHzkpdN9q3OoLC9qj1ZbeO5bibeSCNlty4=  honduras
...                                            ...       ...
1376  NCHu7bbR5E+TwN6aruNFoKeH93HknU6sz9Si9QUnDnk=  honduras
1377  wBhA14paIj5UVs00vOzfGjQX5QqHX44ETRwGV5xMzmc=  honduras
1378   H586CJp3SN2C8H3xlubuNayoooZK5V3Yy3ovuwXLP0=  honduras
1379   Maj5kGMug0RDaWpUPMJ7R57ZFCopUK4LSV4t+tgzCg=  honduras
1380   qkAFvx66BCyc42+BZyJsMlzlbwzZcxzUfczZrE0K08=  honduras

[1381 rows x 2 columns]
62303
indonesia
['_indonesia_IOactors.csv', '_indonesia_IOactors_1.csv']
                                           userid    country
0    zDnJZd1nfFDNtKp4ZdiXrqH32Kk9ILcFqKOeR7G+wpw=  indonesia
1      ppy7RgPL++XXaPyFiGRz1IqNyxZxjxyJS7DkEq3pc=  indonesia
2                                      4776096882  indonesia
3    Kd+bI93F4lxfZ6MvI0MvhzPF6W44FaLo2JqVXVFeUkA=  indonesia
4                                      2436706387  indonesia
..                                            ...        ...
595  R1d3hN0y6wZ2IoO8mXXlk5SoKPNd3r+hLfEWnTqrM0g=  indonesia
596  TjcLOvFbczX26VGLL+9jd1L99B6E+R1pynrQytYU6aQ=  indonesia
597   NaI46rN1D7xv455ZwH4JYX91nX+dZWwYhiaCvvVjPg=  indonesia
598   s4LPViG5Nn5ukN049HyTKQvInlRZhJi7SUOpKbXHjA=  indonesia
599  Z9pcpTJeC63C2OUzsFc73cLvTyNqAGNn58ojRA8ZLnU=  indonesia

[600 rows x 2 columns]
62903
                                           userid    country
0    zDnJZd1nfFDNtKp4ZdiXrqH32Kk9ILcFqKOeR7G+wpw=  indonesia
1      ppy7RgPL++XXaPyFiGRz1IqNyxZxjxyJS7DkEq3pc=  indonesia
2                                      4776096882  indonesia
3    Kd+bI93F4lxfZ6MvI0MvhzPF6W44FaLo2JqVXVFeUkA=  indonesia
4                                      2436706387  indonesia
..                                            ...        ...
595  R1d3hN0y6wZ2IoO8mXXlk5SoKPNd3r+hLfEWnTqrM0g=  indonesia
596  TjcLOvFbczX26VGLL+9jd1L99B6E+R1pynrQytYU6aQ=  indonesia
597   NaI46rN1D7xv455ZwH4JYX91nX+dZWwYhiaCvvVjPg=  indonesia
598   s4LPViG5Nn5ukN049HyTKQvInlRZhJi7SUOpKbXHjA=  indonesia
599  Z9pcpTJeC63C2OUzsFc73cLvTyNqAGNn58ojRA8ZLnU=  indonesia

[600 rows x 2 columns]
63503
iran
['_iran_IOactors.csv', '_iran_IOactors_1.csv']
                                            userid country
0                                       3232244922    iran
1      C9gmIrZupcQJk1i8XC61B13vT4q6CHe4fSFybbpmi4=    iran
2      UtB6T2f4tPSrQ0NjQUew95XRMfcucPf6t7TxvxHJvI=    iran
3      xwqcQi09X+SR9hjOdKtBN0NiZpsrMafchhaF93+Nkw=    iran
4                                       2706416816    iran
...                                            ...     ...
4904  5L1UCK0xFG4HSqlQQHO3G3T3RBUBAAwo2GSkstZYrPQ=    iran
4905  Ka4Bqq1lERtHQOdVR1NxnbC92w10BZRJ9vDEINKzeVw=    iran
4906  bPvGhwrOvQykjsoDrPcEF1zgOZLo8fleIDrsIXI7cEo=    iran
4907   ptgP1TTTvjsSgq5yxgxSlGhktsysdk+RcbfbwwtBoM=    iran
4908  RvDcXqJFnggMQF0SLBh02xZf4ANVc6l7ED25Es02aIA=    iran

[4909 rows x 2 columns]
68412
                                            userid country
0                                       3232244922    iran
1      C9gmIrZupcQJk1i8XC61B13vT4q6CHe4fSFybbpmi4=    iran
2      UtB6T2f4tPSrQ0NjQUew95XRMfcucPf6t7TxvxHJvI=    iran
3      xwqcQi09X+SR9hjOdKtBN0NiZpsrMafchhaF93+Nkw=    iran
4                                       2706416816    iran
...                                            ...     ...
5051  5L1UCK0xFG4HSqlQQHO3G3T3RBUBAAwo2GSkstZYrPQ=    iran
5052  Ka4Bqq1lERtHQOdVR1NxnbC92w10BZRJ9vDEINKzeVw=    iran
5053  bPvGhwrOvQykjsoDrPcEF1zgOZLo8fleIDrsIXI7cEo=    iran
5054   ptgP1TTTvjsSgq5yxgxSlGhktsysdk+RcbfbwwtBoM=    iran
5055  RvDcXqJFnggMQF0SLBh02xZf4ANVc6l7ED25Es02aIA=    iran

[5056 rows x 2 columns]
73468
russia
['_russia_IOactors.csv', '_russia_IOactors_1.csv']
                                                 userid country
0          BQSd6HG5pCEX3Vbw28UJIbW6cDXtu4bgejnAfZmnlKc=  russia
1                                   1149814579293241344  russia
2          uLoGZJaGkQIO04exUS1wFuleaxnkVEWZhumJcU7JjBo=  russia
3           PvMtU8hSwydfwGdw7yuVC5yBPXjIE7+pZi0m0X7UtQ=  russia
4           0biUYz0EYY+ffddjSD8tf7+drN978R+BsJ84PRzqqI=  russia
...                                                 ...     ...
3723  692b1c26f9582d3af67c6b76efbcff7b634f73c99cda83...  russia
3724          YlXS0UKGY8XbAJ0iyGxX6j4d7VNvvPgIyOt0AdWU=  russia
3725       U+FW5yNPik8LFkQ68TPtpzkuLHeNZ5Vknp+ByAi2llw=  russia
3726       vLuUlZyfsZB2CsjcBltyEg2TN5PaAbvFIX2MYSqNZv4=  russia
3727  b216921eeca60bcac315b7ea497da0eb8ff3167729c5fa...  russia

[3728 rows x 2 columns]
77196
                                                 userid country
0          BQSd6HG5pCEX3Vbw28UJIbW6cDXtu4bgejnAfZmnlKc=  russia
1                                   1149814579293241344  russia
2          uLoGZJaGkQIO04exUS1wFuleaxnkVEWZhumJcU7JjBo=  russia
3           PvMtU8hSwydfwGdw7yuVC5yBPXjIE7+pZi0m0X7UtQ=  russia
4           0biUYz0EYY+ffddjSD8tf7+drN978R+BsJ84PRzqqI=  russia
...                                                 ...     ...
3780  692b1c26f9582d3af67c6b76efbcff7b634f73c99cda83...  russia
3781          YlXS0UKGY8XbAJ0iyGxX6j4d7VNvvPgIyOt0AdWU=  russia
3782       U+FW5yNPik8LFkQ68TPtpzkuLHeNZ5Vknp+ByAi2llw=  russia
3783       vLuUlZyfsZB2CsjcBltyEg2TN5PaAbvFIX2MYSqNZv4=  russia
3784  b216921eeca60bcac315b7ea497da0eb8ff3167729c5fa...  russia

[3785 rows x 2 columns]
80981
saudi_arabia
['_saudi_arabia_IOactors_12.csv', '_saudi_arabia_IOactors_15.csv', '_saudi_arabia_IOactors_7.csv', '_saudi_arabia_IOactors_8.csv', '_saudi_arabia_IOactors_6.csv', '_saudi_arabia_IOactors_11.csv', '_saudi_arabia_IOactors_14.csv', '_saudi_arabia_IOactors_9.csv', '_saudi_arabia_IOactors_3.csv', '_saudi_arabia_IOactors_10.csv', '_saudi_arabia_IOactors_2.csv', '_saudi_arabia_IOactors_13.csv', '_saudi_arabia_IOactors_4.csv', '_saudi_arabia_IOactors_5.csv', '_saudi_arabia_IOactors_1.csv']
                                            userid       country
0                                       1902837234  saudi_arabia
1                                       2700336042  saudi_arabia
2                               821067045186007040  saudi_arabia
3        ucrEb4n1hFkC5pdKd2Xvy8LZ78clwfH5jnVRC4ZU=  saudi_arabia
4     y7DO7XZx3otGvf+moKSLpktwkkQCmOmgasLZbVm00Tw=  saudi_arabia
...                                            ...           ...
2009   LErNfbXoiITe4b1USM1GnqngO9TR3UMRFePQ04IAT0=  saudi_arabia
2010   PyHqhVT+SV21hIWKV3R7pXU4+VYI8ZU7ZTHfPAwIR8=  saudi_arabia
2011   9HYhFF1pEO2s8MnpANRbCiNN9bpBuh1H8brBtAEz9k=  saudi_arabia
2012   yzRY8nVzLOj9L6rFHBVU3aJERtOR36uMy19pee0e0E=  saudi_arabia
2013  CWMRUvWB+D3iVeBbVguQg45H0pNsy97kSZlJsGbvQRc=  saudi_arabia

[2014 rows x 2 columns]
82995
                                            userid       country
0                               720513173057613824  saudi_arabia
1                                       2666947550  saudi_arabia
2                                       2479265499  saudi_arabia
3     4Rr+5Ss0UyyrdVDszLulLtFlre1v3RlFCLeYKqoUj6s=  saudi_arabia
4                                        399347336  saudi_arabia
...                                            ...           ...
1526                                    2566085162  saudi_arabia
1527                            964041971567353857  saudi_arabia
1528                                    2188054150  saudi_arabia
1529                                     825974677  saudi_arabia
1530                                     750209419  saudi_arabia

[1531 rows x 2 columns]
84526
                                           userid       country
0     rHppfuKrt8I5lUTPPUjsjbGVT24b2DQL5ykVgKLk08=  saudi_arabia
1    BPzmiBLRbyLAHJnc9t2WzDvAhNrh0GA2k3mqVJHvo+w=  saudi_arabia
2    whSH75NH+VyhPp4j8snGlSGtTyy04vodOWVaYfTTTUE=  saudi_arabia
3      TiLuqTwIPmIjk7evCjjbyQ2rbzomRz22mDt+urg7s=  saudi_arabia
4     WpqY6lIUp7n3rHmvALH+CvjFzH5wpiChyrBiLN7Eg8=  saudi_arabia
..                                            ...           ...
800  jZWWdS6w+Lx1SWREbX54or6sUQoXscxmJQrT3H98lRo=  saudi_arabia
801  nGJThQHp+p9H2Htqskl65C3vk4afJivU2RbOFSav8+I=  saudi_arabia
802    NkZByoQi91lHRTBRc4by+ykYB3f+SiwVAt4xwkAjU=  saudi_arabia
803  UOtCuLI1CJlxuWsqpYe6c0XlaDqznrzdKAduy3gDctQ=  saudi_arabia
804  c91nBEOv5RWTtBe8f6NQ0HTcNFzybQb4MpgwnPl4Vik=  saudi_arabia

[805 rows x 2 columns]
85331
                                            userid       country
0                                        906316400  saudi_arabia
1                                        541880069  saudi_arabia
2                                        455922757  saudi_arabia
3                                        896519521  saudi_arabia
4      Wme5ti76tLHUg8bI1RX2Z0ria2vCablQCTHT1FLtA4=  saudi_arabia
...                                            ...           ...
1433  Grb8ZlyGjF8cLJZlqJdNC7HF88nCu6wjUEZyENnb4tM=  saudi_arabia
1434    d7AwqoZltHOlfFMJR3kjRZf5GlOpzULCnOhJvb0ps=  saudi_arabia
1435  cF5lsyGRGu48T5NHEd8QpOXwhquguPKIooO1trHhESI=  saudi_arabia
1436  np1eOxdxZnVz8KR9WRdXAaxOCMVgkHZlqKMZpQKTq08=  saudi_arabia
1437   CeBSYUSN5CKF8JEuDnHB7c4TXaf5+CqvHQ0MzMt+iI=  saudi_arabia

[1438 rows x 2 columns]
86769
                                           userid       country
0                                       896519521  saudi_arabia
1                                      1908604568  saudi_arabia
2    r4PeKmgVHuCtzff63LB12xml26QzHfLQ2c+EnyP5oOI=  saudi_arabia
3                                       343341807  saudi_arabia
4     +J937Wzdi8rm9BHhh8PwLbyGS9ZCCovxu5nWdTX17M=  saudi_arabia
..                                            ...           ...
713  Z+WxmeFwSr6SjuPpeMTR92B0mSFJtExxsqvxcJeZ274=  saudi_arabia
714   AhiECaiBdXIIJCpVE9FbQwf9Z+MSyiwTJ5AEQeIpu0=  saudi_arabia
715                                      42391032  saudi_arabia
716                                    2457899432  saudi_arabia
717  o2dx4Mq6d5+yELQJmp8DDlO3H3NGlUjvsiX6oWO3jZw=  saudi_arabia

[718 rows x 2 columns]
87487
                                            userid       country
0                                       1585056745  saudi_arabia
1                                        561546105  saudi_arabia
2                                        486542259  saudi_arabia
3                                       3091540868  saudi_arabia
4      XTlA6FDGPdkte+9S4nzqxQGoZZ4M967xwaNmXjpTH0=  saudi_arabia
...                                            ...           ...
2226  7Qmkc7Q+r1HINLWdau6hcEU0FsyEfWOekl58+26xzD0=  saudi_arabia
2227  5mx4glagrpHxbEmPqPxMIJQL2Vj0reAltihUmuCqZJU=  saudi_arabia
2228  qvEIMbS8l12Emo45z41Fj8Y4Gx44cAyEHW3VwgK1nJE=  saudi_arabia
2229   A3PXyVKiRMiq0BTOw2AcBFDiVKV4cfnxM2cpkh9gaE=  saudi_arabia
2230  V1ZbfCP6oNz5sF4bsD0fPBzBIoJJE8NixnB8E55TU24=  saudi_arabia

[2231 rows x 2 columns]
89718
                                           userid       country
0                                      2542282387  saudi_arabia
1                                      1126410924  saudi_arabia
2                                        95690126  saudi_arabia
3                                       714631014  saudi_arabia
4                                      2331659310  saudi_arabia
..                                            ...           ...
379     xPYPKWHkNjXtQa+AWPeWkCw2t44SGTcWbhKXCh5I=  saudi_arabia
380   SbdUBJsXMvjXB+va9zv9QP7e3l5bo2MbO+4seGK8y0=  saudi_arabia
381                                    2566085162  saudi_arabia
382  xW+04RWOtwj37IqzWdl5YjF4fnG+w26SR2R0GE04xDY=  saudi_arabia
383                                     413950033  saudi_arabia

[384 rows x 2 columns]
90102
                                            userid       country
0      mlfosxrMK5ocsNI+elf362kUfIaX7ASLoe8hhzUdcg=  saudi_arabia
1     ccRKlC8ZZZ4LMtW41tFwYskFQqkorC3HTTGdHvUd+Eg=  saudi_arabia
2      m9gPJ4GzoFsVX0DwHPGFolRzBbrZPdLJ+JflExTgmo=  saudi_arabia
3      dKHLFBiCzwLxHGijm0qATuZeqtUjyMrJWRF3X2w6Vg=  saudi_arabia
4     vczripOcvrQ82Or6UC35LhdwjXqWZPGKl+mzXb5dQ64=  saudi_arabia
...                                            ...           ...
2830  VQuUwkpUMXmVAhqYS2ImGvcNWlofm6hORXXP2CsoWyc=  saudi_arabia
2831   CeBSYUSN5CKF8JEuDnHB7c4TXaf5+CqvHQ0MzMt+iI=  saudi_arabia
2832                            909396555605659648  saudi_arabia
2833  Oyts8f+bvCC1gTv8xwa5wUbtFnEAImBG2bKeoR+ayRk=  saudi_arabia
2834   d9NeYtpxZB5fbimEz+a+GjEnd4wemmyPMf0K9sL4dM=  saudi_arabia

[2835 rows x 2 columns]
92937
                                            userid       country
0     p9W1QGZ23pcdIz3BzRipRNRUbaI7LeP0AAZHtzJPAnM=  saudi_arabia
1      2UdkQcmei6KrtJwGDTicGUOoxx67mUuhQNr8nl1GOY=  saudi_arabia
2      dKHLFBiCzwLxHGijm0qATuZeqtUjyMrJWRF3X2w6Vg=  saudi_arabia
3     WapJsE+tpz9uH7SMGZkRACbExob6drMlQ3YOPRRTRQU=  saudi_arabia
4     nGCH+Mt9Qu8TrxKLKyfD6RBuvR5mBkTZQPQhkg4WRRg=  saudi_arabia
...                                            ...           ...
1809   fcLfjGDaiCbwTF0khhUwfkPIUzcuELWVEa9tBMyFuM=  saudi_arabia
1810   uW5Oql+zcHoOohZa88YmI42d7e+P8py3ufdvvLg7GM=  saudi_arabia
1811                            925433852440563712  saudi_arabia
1812  CWMRUvWB+D3iVeBbVguQg45H0pNsy97kSZlJsGbvQRc=  saudi_arabia
1813  4Vl8ZNNT6kNdE4TIo19bmiEQbtMW6tXFdicLdpjZNBE=  saudi_arabia

[1814 rows x 2 columns]
94751
                                            userid       country
0                               726863380917686273  saudi_arabia
1                               737065868908187649  saudi_arabia
2     9YvT23oPgVufPXkZKA4VNj7nKkH9BDtPCrBtzTv2fs0=  saudi_arabia
3     IatjNZ4CDgQ0PmNmSe7rbVaepdxh6VepRqReQHTVQ3o=  saudi_arabia
4                              1101953586148401152  saudi_arabia
...                                            ...           ...
2392  VSDiY43V8vWVhigtsfGtFTbpErk1tDZe2nT9qa10Qkc=  saudi_arabia
2393                                    3274753806  saudi_arabia
2394                            719684828631842816  saudi_arabia
2395  L4IO0ayjPG8PgMcu4wvISGxAOrSYR1bh0N6RTPvW74k=  saudi_arabia
2396                                     435583731  saudi_arabia

[2397 rows x 2 columns]
97148
                                           userid       country
0     cDkCgKehDByE2Ba98+UKaQNqzF6k2pXpmzVfXrE+8M=  saudi_arabia
1     ACstUualFuzyq3MLQpZ0Kr8z2h0kjSgoy5F9DtwB8g=  saudi_arabia
2     uMiDNKqulK5WlAK3NXWj7xjsmxo8+dZHgAozaKlOPY=  saudi_arabia
3     avlB1xCcVhbEChqGryOFA2Ny2AePwRy2AcCPdfvzzw=  saudi_arabia
4     AMIHampUHx7lWTCIiTHO4FJ1pQgBxQUPaxQlcsfstI=  saudi_arabia
..                                            ...           ...
732                            988400378797535232  saudi_arabia
733                            977581891376345093  saudi_arabia
734                                    1695036031  saudi_arabia
735  YZMDJRetb42kSpSADXTmtzGB1AakUFZZrHUlQsgRPCE=  saudi_arabia
736  Q+y50RIoDn8SnVVEfUTQCC6NYAuX3X0U63paY++RWWE=  saudi_arabia

[737 rows x 2 columns]
97885
                                            userid       country
0      tFkrGyBt0Y6+RsF3804yAprEq8tvgK7GDd0ByYkDk4=  saudi_arabia
1     63RQs3DNVUOKxO0CI8S0+QyQpuNRCezZjqe6vgT7JBA=  saudi_arabia
2     xan1w5lwFXlZKSNSNvA3ipKmdWEE3FxS2cPRCnkcnvA=  saudi_arabia
3      7kYD517etwko4SVt1S4y62vwkkM9StOY13w0B5Gras=  saudi_arabia
4     KAYyGSy2MBn+Rd7cMGDD8lQo9lGgLiv1uH7BhJDR8YA=  saudi_arabia
...                                            ...           ...
1492  PmXSX6ySwjmnYTLntKezevF70zl4hHql9g9kOh4OxXk=  saudi_arabia
1493   FNmKnBpMaJWXa9EQcclZm+vf8QeDf3i3kOdeLt1fGY=  saudi_arabia
1494  FqpnKmVig8eAnrIXCLe34qQNb6qlOAMDBKS0snt0UjE=  saudi_arabia
1495    3UPpanQATwepHXzx65bsqeO+Yik6uZ7P3iDvyi3IM=  saudi_arabia
1496     b5C3o6uq+7tvuVQ+maZrMeHCiL5otP9I5igpsJA8=  saudi_arabia

[1497 rows x 2 columns]
99382
                                            userid       country
0      lxl8oYl8VnFTNJtnpolzvvLzevm6c6eJq8mu7kcOJ8=  saudi_arabia
1      LOQUMpYXd7JdXz9GXSqBkQZwYH54C3ileVgAu3d2dg=  saudi_arabia
2                                       4708503082  saudi_arabia
3                               772907853015384065  saudi_arabia
4     37ojjyjV0LT7zDs0KOEpTZxAZFIjEvXlbKFSWfTj718=  saudi_arabia
...                                            ...           ...
2275   Qmpv26O0E4z7+ZwZu2DR3IndUgoZFnlPan9du1G+4g=  saudi_arabia
2276  09SpUJLbQXRpnlrE5Z3bNW8bg17Q77+d8P+o+Q++oa8=  saudi_arabia
2277  tUrC5fEA5DYLdeu1xkWt8IzLbEm24GyWARbFuzKXSi4=  saudi_arabia
2278  EdnDXfShgrJYEEToCjBZFszq0wXCTLtRMtEPoHJbs94=  saudi_arabia
2279  2KaB6evd6m5JiKhiZo0YUbiwMooN8aAGnyLfpDfbNkY=  saudi_arabia

[2280 rows x 2 columns]
101662
                                            userid       country
0                                         62459349  saudi_arabia
1     RSz4THI7iqaJdN+EMMQA1cZOizvUcovNqjkk7DZjKfM=  saudi_arabia
2                                       1585056157  saudi_arabia
3                               853455302527778816  saudi_arabia
4     JkR7PXM3KghaDXp5Of79VvrtZvC4l2tzXeifrIT54jA=  saudi_arabia
...                                            ...           ...
1975   puyJqiY3ZeLkEJ0HrrQuIJBUgb10z2GPXmzYznvJUM=  saudi_arabia
1976   YRSPKQNLAPP+Stt8Etr14SD25CoZqDASkO6p2I5TIY=  saudi_arabia
1977  nvwh4U80CxFHMT+87yrGlPBGAz35WksxGbYP+OiY6qI=  saudi_arabia
1978  cWEllESxvAGkWNUqYFlLVi5N6hoPTD0LEfvpFvaUg8E=  saudi_arabia
1979   aWi12WIXbb7rrXMwcTW7euFwXMHa8ylFpznIJF1gUA=  saudi_arabia

[1980 rows x 2 columns]
103642
                                           userid       country
0                                       413950033  saudi_arabia
1                                       328240081  saudi_arabia
2      3UPpanQATwepHXzx65bsqeO+Yik6uZ7P3iDvyi3IM=  saudi_arabia
3                                       193076013  saudi_arabia
4     OF0VE6pC9ESb5cs91Mzoo1VHnaYdmILpuWbqN2bnZQ=  saudi_arabia
..                                            ...           ...
553  CDzB7h2m34V18fuvo2py5zrKILW8VPEnTWcRuTMF0sI=  saudi_arabia
554  qOdpK6nvuB3+rppNYx+bxlftCxd6CWRkGj6LGEyIFRw=  saudi_arabia
555    1SML95gBs4cdsYf1NWwpv46m+g+XSzcMz69lRwc3o=  saudi_arabia
556   V9Am6N9BKcd+060R1OobfMj+HlHZpQXCiYYCoRcel8=  saudi_arabia
557  YvAvy9Yjw6Q2EuJTuUWC43cd3lPSdXdrbQb5hss2D+g=  saudi_arabia

[558 rows x 2 columns]
104200
serbia
['_serbia_IOactors_11.csv', '_serbia_IOactors_1.csv', '_serbia_IOactors_5.csv', '_serbia_IOactors_9.csv', '_serbia_IOactors_10.csv', '_serbia_IOactors_15.csv', '_serbia_IOactors_13.csv', '_serbia_IOactors_2.csv', '_serbia_IOactors_4.csv', '_serbia_IOactors_8.csv', '_serbia_IOactors_7.csv', '_serbia_IOactors_6.csv', '_serbia_IOactors_14.csv', '_serbia_IOactors_12.csv', '_serbia_IOactors_3.csv']

                                            userid country
0      F86npupQ0JAHjrtf9sH8l+03RQPjws2aMvi2EqUp5o=  serbia
1       9glSGfkRM3VX9cyM9+2+A5PnhRUbEccQhB0bDsKX0=  serbia
2     zZ6JQOsPDu9uREDCkxcI4qezYdu34QCEj3BgqbGsytg=  serbia
3     hruQiCAv4AzH6fReoqrn7jmBcSCxSxy3+zdjFksb6Ik=  serbia
4     fDB+HOj7NxHx5O4VpgYvN1iW5dgpcdpjYfqqO1Hb4Z8=  serbia
...                                            ...     ...
3196   uRmVLJScPB9s2waqG1IFhIq2Gco9qoLPWGylYB3dTA=  serbia
3197  yftc7Unqmk2HbnVFDGeFXi49ISbLZyBisLU50Rg1d58=  serbia
3198  ZIrl2HeyqaYkMyWp8eIz33MqaXKkxPDQbg5w5nqyrvU=  serbia
3199  MJKfreYKZBeNavmUnlE77buvAPj9uNEbQajfBNUl8Jc=  serbia
3200  SoHbjqt0klYC+RXXUZi92jWTYQE+iU19qvIPnY4ETBM=  serbia

[3201 rows x 2 columns]
107401
                                            userid country
0     eI28QUDeLPg2Zx3LCKzBNgxfNbD0PubproNLuHh6N1Q=  serbia
1     V1xqvUkJxnPksNTOZfCN37rqRrfCTp8BVie9nXLKiUI=  serbia
2        nq1lhyREwN4M8pQKoGMyEAlw+p88hL8stdiY+yhE=  serbia
3      1t9aUI4stWRljEI9ordrr5vukgKm0ckTidZojecihU=  serbia
4     2Isi0r8PdGwmEi4oLVw13ExkuF0miTmswEvlrRHzjMw=  serbia
...                                            ...     ...
1368  JExQijFin9frLgtF+cRJ0E+7H+ppL0Qqgdn2OC4nvsA=  serbia
1369  H5CwwEouJDL5qc+w4vS92ocfoWAUFScadLC3MndX6vc=  serbia
1370  pVyqsxOqzdWOMlaA7I83ByN90kBpNAULR11jE92FziQ=  serbia
1371  irG9kL6nqNTjO98tf6FUG2cd0uhc3L0eQWpNXZ0u6DM=  serbia
1372    f5YkSAmjO04Lba0P8MUi9dX0q07691FEYj4soBcGY=  serbia

[1373 rows x 2 columns]
108774
                                            userid country
0      t2PR0QSbfzmEZll6wxuDPAUWWp8RxqscE7h0ZDMGQQ=  serbia
1     t716iM6VkntbPOI5zbWKpFVvVsYqVKoqdHNlBMKuc10=  serbia
2     PoAn7HuJzCmg2mJAzGj1dpNgc5QJ1At9x49trtBRWAc=  serbia
3     PueF6vMEuPexYRqsJSdB4999Vq2JZ3NK3e+uiEiDBeI=  serbia
4     ZcHe4tkbO9CtqjkGrsiqnB6cnHqy9BdHdWiX+cxeX70=  serbia
...                                            ...     ...
3262  R9LN2ZVyrwfX3tkYMkElXY+w8hOaHXpTYk91d+XcV6k=  serbia
3263     n26l0QylJJ9xetdFgY4ssUsmkJuRtoiy+JmMG6SY=  serbia
3264  fXKZkGVdQsN21chuYzoaqnfgu5+v3kfSMsD6tf6gMgw=  serbia
3265   Dwd8w8DdCnKlVXR4xbrX4ktArX9Y6PVyPESyPM8iMM=  serbia
3266  4+wuMbDnpIwB7xspP6L+qf7NHG95g+owJeZwYf+HxKY=  serbia

[3267 rows x 2 columns]
112041
                                            userid country
0     i6EM93KpBNDylIjujUrLssR09xr636ta7cuNV2tQ9BE=  serbia
1      BaDk4DGhNGjtXRceJ84lQ+hBIWlhAfjHEC0S+xhABk=  serbia
2     0p+3CLqT2o4yeRJodJAA13ZuYEbgllrd4kxYSbFfaTc=  serbia
3     2AbJynzlfZNl6L4AVhU8Mu7H85rs7t+TnpDE4G6mJSg=  serbia
4     4YFRiw3rSpWVwroxf9zCMr4bOplB7yFEssIjdbRn+Y8=  serbia
...                                            ...     ...
3251  HgeUBO+YKcfWs5JfAlm7TbSBsOHTR5UD0eP5YwmnFS0=  serbia
3252   bTTCRCvfV5g++dWOOWYdV+MpXLQGPQIyezI7AUK0so=  serbia
3253   F70ioHXmM5EbyuKMtVT1ic3Y6QznWm+FaHw4jWtCJA=  serbia
3254  DZuZU0o8Wn4tzis28cQSjd2aDGPzE7WWfe+cwLNTEP0=  serbia
3255   bFNAnbPJvLJn2jN945E58KLsLXh0OVX1E+5BR7rbXM=  serbia

[3256 rows x 2 columns]
115297
                                            userid country
0      fU4mWsdkTqvtO1auzSXUpONEhs4BhxHIjWNEXDKrJs=  serbia
1     Of6FyLN1JIcPj2SIj60vZwdDBT5LTINUkqNXg70wpMc=  serbia
2      e117tXAhpSHUrdO5BzYmuV9SHALWot6OVLyUeavFYk=  serbia
3     GBj66PnFKDwB0elMAE1loi7vs3TDs21WWrfpWFXRnuA=  serbia
4       H5Tuq87L0cs52zOv3cMgM7dyd4tBeuikOK8XXLYxs=  serbia
...                                            ...     ...
2834   7BBRUr5GhAQqSTpgOrdn+8i9IbOKULPsKj1eixeAHo=  serbia
2835  mI2woljx6etZeztB0pVQTmh+SZQHz6muNHoWTUMqdVA=  serbia
2836     DLcQP950qne7kyg8bKRs7fCFcWc2SwZdov5ooAeg=  serbia
2837   sTsU2aTLVDzVzfy+JcDGdtqG3HKHFw4G7pAaKAPhlU=  serbia
2838  35DgdObsSYhQgXiDjwE+r1I+ry2ZEifYr6YFRdUOSw8=  serbia

[2839 rows x 2 columns]
118136
                                            userid country
0     0wBQ5PyCDrNDEdtSWcHyPAnGF3kU25gOLO5IAh8LjTA=  serbia
1      cy5VSFHBgWeV8bqq+p5GLsCDuDbtsLH1SPwOT3hpY0=  serbia
2     JvJtI77fw0VzqvUJUihLHewwmiXFviytsx4yuALLupU=  serbia
3     eI28QUDeLPg2Zx3LCKzBNgxfNbD0PubproNLuHh6N1Q=  serbia
4        nq1lhyREwN4M8pQKoGMyEAlw+p88hL8stdiY+yhE=  serbia
...                                            ...     ...
2185  Phh7V+FRPkVHprUhzGnhfXCbjdq8Y2V3k4J59mSlAjg=  serbia
2186  rLMINLmNsMmgFgZMPDgMXUIBUL6EKRRLog+OU4p3hzY=  serbia
2187  SVFiyhHCDo8qagNepd8Lh4TKiENtorXKxdMi80iTTfo=  serbia
2188  dHeSPw3BUB9+CIVWEbBeesvWvLER113MZU+ZoBath68=  serbia
2189   Eg8suRBZa47TIdbgQnFc8GBAEoN8YGtPw0xJ+gzRWk=  serbia

[2190 rows x 2 columns]
120326
                                            userid country
0      pS+pRRWZ9INXWkqG++Vx6GmcNiYEV0u4lRJ9AYuHN4=  serbia
1     r52VMUhfz5nA6oYLPoMGjQ9UwY9wfBIOgaURcoBhVAU=  serbia
2     84z3dFkdBom7cfZlbzZnoVfjUylbmDAkePG4Ojf2sq0=  serbia
3      XWdN30chcetp2GB8RWL5pAaEcXkHCtKKjjdWzT8Qa8=  serbia
4     h2zXwLUwpSsn3UyCdAlvhmJ8bhw3SvvcF5hNo1sY0Ns=  serbia
...                                            ...     ...
3749   MtE8VMH2pmxg6IjXsW2QEluUh6jBqZrI2Cf++IwV0Y=  serbia
3750  cDI3fOriHxi+C6epH3v4h31YlMARQcwgEZ0PDNhbQv4=  serbia
3751  vuK7ShYLQMaTGHa4k9BTKx5nl44J61sc2dXQm9n3xfc=  serbia
3752  e02h6BJ4E8eI+iKpm0uzqTjPXgS906cBZjlMwbc5mS8=  serbia
3753   nOTIXSKy1XNarVuX5rWfnxHnv4oa7MqbGklFG3cEwo=  serbia

[3754 rows x 2 columns]
124080
                                            userid country
0      zqxf8XjmnPUU9ub4Ru35brXQywxZRCLbCKb1Uaoahk=  serbia
1     adusaKyF9MUK7279yeUUomCqDwoe67PEZgDKnABibsI=  serbia
2     Yo9Py3ox9UarTH6pG54lKaI1VTKfTCSlaUtq9JrBTYU=  serbia
3     aP30ceKEbwO4rAOsp+Fn4a+9Um0yrQHZfNmDKh2uQGc=  serbia
4       vfdDwCUtje0B+8au177DXe0NuT74dx+mr9+ycWTW4=  serbia
...                                            ...     ...
3384    Jq2WCWIDDR9e7VPKKHu16G7pO8jLIcLkQuWfpZdNQ=  serbia
3385   mAiUbID9yfChM+nRHmfZaetLTCPIJZGZj+ZQIY6QJc=  serbia
3386  U1iJvxiwPVCkwaZT1Wml1YsVG2TqgKobQ4CPzBmKnp8=  serbia
3387  kvxaV6+kX2EAsOatAIzU52ZUXBCPWjTeFMwnEAGyQZM=  serbia
3388  uDKN1NDKcAqxlLGThVnnskidb4Ls4vsv+rJDBRzzMvU=  serbia

[3389 rows x 2 columns]
127469
                                            userid country
0                               822782327352950784  serbia
1     jOI5LK6dKqAg6Ia9JIHq+R6nJQ8rz6JYKXJwg+bophM=  serbia
2     GQF9xcpgQnUdj9V5dxM5P7faYd+9TpLpBkmXczgq1CM=  serbia
3     NHsfgHiJo7nWjFOza3m9GK1CSRbidPGl7T7myLTpLHY=  serbia
4      MelGQHDZzjjjK+kY2tGTbTnyqltIIWTtqGB5EFcgdA=  serbia
...                                            ...     ...
4142  FMNqUvXUVuMDV0X2bbfKxKnBe8Uj8hih3rCTtyoO8gk=  serbia
4143  7ydY4AZ2ECJv9NhXKLK5pk+wWJA9wTnDiL0QFA2GD18=  serbia
4144    OhXXM3ufit82oei2qHWo50zJaeTH4lG5NslaRYy8U=  serbia
4145   faHiDUb7xfg3L1WcKD4tgM57yIUgFMYXIK8xEak6RA=  serbia
4146    h8AItfO7PqyDdwLFMDc4wdW5IFjXT7ZK3Ovw0gGV0=  serbia

[4147 rows x 2 columns]
131616
                                            userid country
0                                       4846116969  serbia
1     tHqXbkWjFWYJIkYKQjqUbvER5wk5+ZSZtZKKI6HgLB0=  serbia
2      bbrTXWUXaABmaqtN0YZOlkQirwjyWGJPoRS8T6Tvdg=  serbia
3      3e7knqTMAgBwofgW8dXgKx4AmrHjFNk9SFvyM2xpuU=  serbia
4     Dv8CAin6PPK8hERRoky9VpbVPds6CLEIoIaNXxrbgpo=  serbia
...                                            ...     ...
4163  CjbaloNNHTyNcV3dk5Y5au31eEfRGY9j5LZQduLbcwE=  serbia
4164  3Aa7buVQziy0BmoeaHW1jIq+zF7q89Osp5bsYteFcTs=  serbia
4165    npZqMQ9JvEXISyDcPxWDyjGaSHXDzJta9BhiDq5gw=  serbia
4166  WJ7aA9L5mpLUceLaef3Ky6WywRKJLMveZYm8eUKcPXs=  serbia
4167  FA8Id5WTTbIMvlHGKgeh8iPZ6O4SzcixLxwynRSKoXw=  serbia

[4168 rows x 2 columns]
135784
                                            userid country
0     YP4qlUrpKCebFdDK3UXEeWJlP7CozDXtSfwYl72CxHc=  serbia
1     Li7AjWlPe3bkW+tK62CQqhcoV9Uu0a4eDsUXDrNZRCI=  serbia
2        3S9pS1H9NxQMzLlEXGYO0xM4V+5n8F662D9KiO2E=  serbia
3      DMcIHiuYyGCjk4P1Qs3F5hBGZ9C8aioHfXcB4kNyJE=  serbia
4     3eveJKSEpXVr0LG4JKPXE5F3gGrFhLa5yGJmSuo01mU=  serbia
...                                            ...     ...
3200  lAATpBGs2N7KzX3Nq90f4tZfxTIWDrY49rg7DRodVbY=  serbia
3201  +T4G8+fqEmR85jBYd+9qdmsepYjibPPxJY1hO+5zDn4=  serbia
3202   xn6hrJPoIROaiq+uSGBR8lziTiPD+91ntREAUz8uPk=  serbia
3203    Pk+hgX27jCTG6v24M9ykiJIJFa2MpsxnJl0fCwi3k=  serbia
3204  MkNnpg+VkIlfV+dsIF88T3yuGhvkUyXKRBa9U0dgHnA=  serbia

[3205 rows x 2 columns]
138989
                                            userid country
0     5pH21pVgNjGSDtO9Ew6J0cfqmXSCPVeaRUloMKEtRsk=  serbia
1     r52VMUhfz5nA6oYLPoMGjQ9UwY9wfBIOgaURcoBhVAU=  serbia
2      pS+pRRWZ9INXWkqG++Vx6GmcNiYEV0u4lRJ9AYuHN4=  serbia
3       u7+0guJDzzhdwZ0ktgYcTkmqAPjFpAOGxFDcNK+4Q=  serbia
4     ehPYmD+OqcZ0h7NUgVnB51Yu6ydkoHAO2YzjLANb6dM=  serbia
...                                            ...     ...
3650  Myasn+7oW9ya+tv8ORMWezulCDF4wTYxnyZMexDtH7o=  serbia
3651   sGY+zwY0yEebv8eS37X2unp9hFJz7JecA2xZ1XZWio=  serbia
3652  f1WDnqU6leIGQQRg9HJi0qHmq7aENfnDkYOnyJa1M2g=  serbia
3653  CjbaloNNHTyNcV3dk5Y5au31eEfRGY9j5LZQduLbcwE=  serbia
3654   IoYS+Z92y1JBLGtcyEdNGbn54buOfMpXosA5xyOKy4=  serbia

[3655 rows x 2 columns]
142644
                                            userid country
0     MM8HqOFfNuOF5xuCrA1sgC60sCnz1LR6eiB6K4RZ53M=  serbia
1      efTV901pwxbYwxgxQo6KokuXIXJNMBs1uTKf6Mmnjg=  serbia
2      qCnqsOy3wlbO9cuNhP8W3HajRD5CeaxPe5hUZul4pE=  serbia
3      wnZVhAXsKBaioB00ZVdSwm7n1dUCd0CEIxq+oE8ILA=  serbia
4     wXUtn5LsP4Wg3TJ5T5yQQd0QSvjTYl3ugNMoc8EEv18=  serbia
...                                            ...     ...
2427                           1068117929647058945  serbia
2428                            919877729515814912  serbia
2429  SVFiyhHCDo8qagNepd8Lh4TKiENtorXKxdMi80iTTfo=  serbia
2430   DH2ApmCbH2bYxZBuutA67LKHxS0Ndm8FcwdoEKdry8=  serbia
2431  Pm8WlAKYkhTGlFMOZ47o01nz2jFTWnXccMLT3zynk0U=  serbia

[2432 rows x 2 columns]
145076
                                            userid country
0      RpEog7rbnwhyi5vgTrWsaXCEsb8Jqi6+4ywT+WxJFc=  serbia
1     YTl3UwG+C7i6ofbCdhJDFwjBHKFai0rcMAzn+rpN+yk=  serbia
2       TCzQckq7xfQF04FFtsGj01NXDklaw1KXzxXZ5e5yQ=  serbia
3      mWtuAil5Wvjyp7g9Ikeogz3yvLCixKSSeoJVtXWpQU=  serbia
4     mXUmvSmQgMnXKAv0Wu3vA6RqPnbp+gwXz9uyuKBOusI=  serbia
...                                            ...     ...
3674    LzPsObj4X38X5JrQ7HdUZotuSogFA2a3odzxtnl3A=  serbia
3675  xTv4AzOA5DI7vI6KGLRCbjngfedRVR0KfjvSVwQUwQc=  serbia
3676   1VVVDcRjAFohBGc9ELJkvuOetSTwwotvZ6ggBV6P00=  serbia
3677  gEqvJkdxNdw+HVL090QUsFWxNu2MlalCbW0YMLlpy3g=  serbia
3678  UDfHXVERL1vORR3efgzBNsB2Ht40H7aflSVR0CAV3I4=  serbia

[3679 rows x 2 columns]
148755

                                            userid country
0     oGFRlAJ31ePdEAxcRiesGmWo0l3Jl2akHxy7HrBhuv8=  serbia
1     yJvjDKC9tcEiuGJ5338l5tQiz1Cw0qSnSYBDGLxvBGw=  serbia
2     hYfNhyFNAH9i2yoC7PcvgeST1B8lWrxeP7uEx+nR+jw=  serbia
3      8ytKxh7ofJkvoxB45Xxg3adRA48YaQf+cCqRgyUTbg=  serbia
4         W3LTA2j5N3c3fDd5X9nJllQhS6Jp2n7iwHudjbM=  serbia
...                                            ...     ...
4086  AhGSesj24BZ4T8bOU+c2C+TxPR1EJeAMNVJdX48hR8c=  serbia
4087  t6qozQBLouUXU4d3Ibim4inEzOOwtBpBragfpL6PkeI=  serbia
4088  iVOpIApSTsX+PMBGdw+d6A+0ONX0jONBnQZj89X9bb4=  serbia
4089   vey482PgwxiUbl8m2hrMjg2W6dh7XAx+VPFuAeeMGU=  serbia
4090  jcLeNsKvPqGiQ2EvyCfVGxHXdcLdzuZAbuIdY8Pn5zg=  serbia

[4091 rows x 2 columns]
152846
spain
['_spain_IOactors_1.csv', '_spain_IOactors.csv']
                                           userid country
0     HZBAyWVCwg5399e6wDmVBGEOu765qkfKvEIBbCuMZ8=   spain
1    IkfSZRNh2ZYiA5pBE3ANkU4V6W1Zy0MCg7TS5UwkLAk=   spain
2     r8pjHZeZGpdBadlVujpAA64tp9Rm581MtiB7aWnWyo=   spain
3     Xo0MzZQt02jWDA1hQOECg06wECXHozTX24FiJ0Ke4o=   spain
4     drkjBGuYxL0S3yExG1orhCvYpvONqdLrdzfrDRHtbg=   spain
..                                            ...     ...
143   RxWs61Dq5Z0SIR5RpNJjErOGroDc9FCekc3jJ0GKAI=   spain
144  Bif4hHy802X8pWfHWIV1ddMP7aZiUtJxgfTCTPrL+wY=   spain
145  3kqDxfp1619Fq6svOwizh3Fckna7KadQfXadJeh2vuE=   spain
146  yUwMni2Kv4dG1uLsUI1pjCtQaKjuFMnoCf0cIX41o+Y=   spain
147  +814w93PbKeKKFtMS2+XiSl1AN7omWLDkYPvRdwINBE=   spain

[148 rows x 2 columns]
152994
                                           userid country
0     HZBAyWVCwg5399e6wDmVBGEOu765qkfKvEIBbCuMZ8=   spain
1    IkfSZRNh2ZYiA5pBE3ANkU4V6W1Zy0MCg7TS5UwkLAk=   spain
2     r8pjHZeZGpdBadlVujpAA64tp9Rm581MtiB7aWnWyo=   spain
3     Xo0MzZQt02jWDA1hQOECg06wECXHozTX24FiJ0Ke4o=   spain
4     drkjBGuYxL0S3yExG1orhCvYpvONqdLrdzfrDRHtbg=   spain
..                                            ...     ...
143   RxWs61Dq5Z0SIR5RpNJjErOGroDc9FCekc3jJ0GKAI=   spain
144  Bif4hHy802X8pWfHWIV1ddMP7aZiUtJxgfTCTPrL+wY=   spain
145  3kqDxfp1619Fq6svOwizh3Fckna7KadQfXadJeh2vuE=   spain
146  yUwMni2Kv4dG1uLsUI1pjCtQaKjuFMnoCf0cIX41o+Y=   spain
147  +814w93PbKeKKFtMS2+XiSl1AN7omWLDkYPvRdwINBE=   spain

[148 rows x 2 columns]
153142
thailand
['_thailand_IOactors_1.csv', '_thailand_IOactors.csv']
                                          userid   country
0    vb+LhxwPwUc6HIMuwuy9yk6sagFdDIkgu0KP4A9dkQ=  thailand
1   NUaMjZryhC4ek9IOuboDQY0Xr5zAkBn6LyFDSpsbr6c=  thailand
2   ejXhEmc73vUyxsDMVwmz8bfrQd0mTE0jAMAFlzZZ6L0=  thailand
3   ZczSdkafT15FHhVyQ8iQAYmugCtFwsLU63fNvzovD94=  thailand
4    kDZ+CvwmOPX33H1vdTA7LBtP76VdiIfcYAHqdOcAwE=  thailand
..                                           ...       ...
71  kEHv4s8f9bn8mmf4cqFbJzfdkE51R1jGyQ9LToN87h0=  thailand
72  8crTeO0XjreawKU5icKZVpKyaGdB4vo9LcprMCo3XQc=  thailand
73   KuNd4VkGaY8wjfE0riNY9M70+EUVs+ClWqwhMVO94k=  thailand
74  yxXsyp1DeGawdE6dxnYzWVx2m3g0r7V+eBSoCX4d35E=  thailand
75  vx6CaKfbFhGJw2w+4b1xLrYliU3LgLf0spQ7sIimym8=  thailand

[76 rows x 2 columns]
153218
                                          userid   country
0    vb+LhxwPwUc6HIMuwuy9yk6sagFdDIkgu0KP4A9dkQ=  thailand
1   NUaMjZryhC4ek9IOuboDQY0Xr5zAkBn6LyFDSpsbr6c=  thailand
2   ejXhEmc73vUyxsDMVwmz8bfrQd0mTE0jAMAFlzZZ6L0=  thailand
3   ZczSdkafT15FHhVyQ8iQAYmugCtFwsLU63fNvzovD94=  thailand
4    kDZ+CvwmOPX33H1vdTA7LBtP76VdiIfcYAHqdOcAwE=  thailand
..                                           ...       ...
71  kEHv4s8f9bn8mmf4cqFbJzfdkE51R1jGyQ9LToN87h0=  thailand
72  8crTeO0XjreawKU5icKZVpKyaGdB4vo9LcprMCo3XQc=  thailand
73   KuNd4VkGaY8wjfE0riNY9M70+EUVs+ClWqwhMVO94k=  thailand
74  yxXsyp1DeGawdE6dxnYzWVx2m3g0r7V+eBSoCX4d35E=  thailand
75  vx6CaKfbFhGJw2w+4b1xLrYliU3LgLf0spQ7sIimym8=  thailand

[76 rows x 2 columns]
153294
turkey
['_turkey_IOactors_2.csv', '_turkey_IOactors_8.csv', '_turkey_IOactors_15.csv', '_turkey_IOactors_14.csv', '_turkey_IOactors_9.csv', '_turkey_IOactors_6.csv', '_turkey_IOactors_10.csv', '_turkey_IOactors_1.csv', '_turkey_IOactors_11.csv', '_turkey_IOactors_5.csv', '_turkey_IOactors_3.csv', '_turkey_IOactors_13.csv', '_turkey_IOactors_4.csv', '_turkey_IOactors_7.csv', '_turkey_IOactors_12.csv']
                                            userid country
0     E9ZoRqZtcBataiZAYmI5Hy+PGq8JvNo6Pgkgkh37HtM=  turkey
1                                       2765536403  turkey
2                                       4609724483  turkey
3     D4Y5diz3k4kq2S5HnW0wGYRaO3Jys3dW6Q6jPwn6gBI=  turkey
4      uJ+l8rnMPJ0JF7MOEDadqtd5MipV29uOG3xUAbGldg=  turkey
...                                            ...     ...
1741   VaVaOX7LqkmP2z5sLNXUdKxBBunrGCRwFw+ySJxcwo=  turkey
1742  to8kxjD982Js0TNCdI3DosueWXwjBt2bl+LbVEIOtT4=  turkey
1743   y5DAorkYONJ1LcRS3xHrkozOWDUlkKIrK01DtzQ8sA=  turkey
1744    jmNVUNAacEHTgqyivUJLM5DDQ+qv4T6DIGNKgSnIg=  turkey
1745    8WrgC0nDxYjrPClr+xiEBSC37t6lfxC10xA5JS69I=  turkey

[1746 rows x 2 columns]
155040
                                            userid country
0                                        117403118  turkey
1      +hDevfLYHW+KKyZB2RpWuUQsfKv78hAIgmlHFtyZa4=  turkey
2     Et83HtJN14cA6k5SVUEi9thyyClr4DIj43brhOJTS4w=  turkey
3                                        378546115  turkey
4                                       1512112903  turkey
...                                            ...     ...
1478   zhX84fR+RwHln8nQSKiQRvxzKYjkp0dRxbMVAWC30E=  turkey
1479  N4Dm7BGEVm+2h2M0j4WWZnamwiBDaoKqhuzcsVG803E=  turkey
1480     4NNHXcJ2o+zFzU2RIf8N8J4N17JgmwcYTLo5k5Dw=  turkey
1481    51bXL6DXBfVHUjKBEp5snJBD29hSNmnn82FkKyStY=  turkey
1482  IKMSIJWGiIJoFPMJ9RUrs6+yKeNYVWrCHgkcJgYHKU8=  turkey

[1483 rows x 2 columns]
156523
                                            userid country
0                                        212203687  turkey
1      ggpc50i1ZuFbf3SnBxV0siIJ16pzffDgsK5v6Olu5A=  turkey
2       7cFPPgXxAe63D5Fi2mr1ohvzv67Pw2RmjIIwWtOvk=  turkey
3     VSE+5G2SIijwMpQX6rkL2D45YWsrSZgwMWfre5qJ0gY=  turkey
4                                        199808078  turkey
...                                            ...     ...
1473   B0fitOS9N9RN51anXtDkfbyz0wzry9Wd6iyL6BUFrg=  turkey
1474  aErrOMGCIOiqBU3w8aJ4uR0yASAJk8tk7980lF+vq0g=  turkey
1475  CJFzIsA07ef8q9wiBFSYSVxb1fR0tDHsiTMyYgfdf7A=  turkey
1476  0AXk1x9FECEZEN9Tx0hAymNrvIu05ozGQUrVBoYiobM=  turkey
1477                            950428205881724928  turkey

[1478 rows x 2 columns]
158001
                                           userid country
0    t7igbXzWiKovOGvUcrO+eVlltB6lGpA46FQOvrmbm+s=  turkey
1    a7NmQfxuZhooONlId8BkDcH62TTRubkEDVZVk8iOjuA=  turkey
2                                      1919934667  turkey
3                                       569412418  turkey
4     M7UVetvXBB5YXDUuhGOeq+KMQCC5lfkJcpgAsK9BVk=  turkey
..                                            ...     ...
590  l2pm1T0rRaQaHxWKBXBvOyiMZrV52ccvsRISBdlf2jw=  turkey
591   3Qu6MIbt9LlxDrlSe81rIJ3oP3oarHwcGA+SZxMjzo=  turkey
592                                    1261584524  turkey
593                                     315764908  turkey
594                                    2900851046  turkey

[595 rows x 2 columns]
158596
                                            userid country
0                                        635452378  turkey
1                                       2871995935  turkey
2                                       4038307756  turkey
3                                       2402710924  turkey
4     uMnrcrsdDpQ2kGX50mWhplA0KvUE1BPIkZTytlwFcZ8=  turkey
...                                            ...     ...
1836   rVvXxRiu8m8PCzP9OCmjLC9WbeuYShUXIqlH199nLM=  turkey
1837  8Xdwjud9DoogMbof11gv8IqQ3e2l4XZAkp9rGN3pS9M=  turkey
1838   VwCnX0soLPA6Vp+rGvw6JnwSI+hHyDpk0FckXGvB1c=  turkey
1839  8RLjpKcCV8RAmHoxZb18e1z+yhdC9Fe1z5h9FhI2w9I=  turkey
1840  RQrRPiUjf9WVU+gpjbyfuHpajlcsam52uPQmNouRuMQ=  turkey

[1841 rows x 2 columns]
160437
                                            userid country
0                               733010741645709312  turkey
1                               789162789700902912  turkey
2                                       4297382063  turkey
3                                       3536966117  turkey
4      sluiTo4AyexNEoCFLU5eDR4+C0DJb2zfv07aBiTnVo=  turkey
...                                            ...     ...
1264  50rWG0Tr6PoJVJrk2LXIXBkGEW02XT1uKMe4duWXoj8=  turkey
1265  CUW2Irl2qifX2kVhfj++1JKOG7NhkTltvQuBQk0jru4=  turkey
1266                                    2782292576  turkey
1267    51bXL6DXBfVHUjKBEp5snJBD29hSNmnn82FkKyStY=  turkey
1268  bEDftdCKa3cbU6Tj6ELcR5LepOEBd3TfCZq6qs7GuY8=  turkey

[1269 rows x 2 columns]
161706
                                            userid country
0     mmzqnzv6dpDQS75m6jyil1R7oagYlgvkdKVA1u0Hx3I=  turkey
1      BeLAiYiJx0LDlAkqui4ZpJHML8oXcmAG4nKQVRYUwQ=  turkey
2      Hy1bHMGnKxSBXcg8+FEWF9K6bm0D93tex6PZbJCbGA=  turkey
3     9MrRJ3XlB8DaY7Jn1cp62TSZ6lOq7XS1wWdLgTzGjt0=  turkey
4     KJ6bX3VcGzpmvmgAcQxqqN2ldnOsW7aB5iqU4XTUKw4=  turkey
...                                            ...     ...
1697  fFHL5QyEsAWyS9yQilagSGtmB31ZLj7HxXoQ157mGp8=  turkey
1698  7AX7Or5XHn6i7FLTYOjUI5NmHgZgJfRmEeOSRsOGHL0=  turkey
1699    51bXL6DXBfVHUjKBEp5snJBD29hSNmnn82FkKyStY=  turkey
1700  S6uYSoAOTTsT3dHMCkMAigCoyAaXcBXc+EpUw0Llv8o=  turkey
1701  b5VkORhSyNZZ1zvelbhhUjojBASR+uMdbZYkMKQw+A4=  turkey

[1702 rows x 2 columns]
163408
                                            userid country
0                                        512283231  turkey
1      Im3LNtp+spGEHltpt0Tt77WSC02i4tNn9LSPyDWuSg=  turkey
2                               754701126503698432  turkey
3      K4PdqSmZZq6zdTscz8QPLuUI2mxNoLinhTmcw4gCQA=  turkey
4       ovbNUGoP9Ith0YG+atx540V+yaPqnuG75Y3IhGdnw=  turkey
...                                            ...     ...
2339  fobunhXgf9mcYgd3GnFbqjhWdOknnlELi+oEA0QgH1A=  turkey
2340                            726734964998443013  turkey
2341   9E7gp4MZu8zVihB+oyPFgEWj9CkPI9udVTarOcpPko=  turkey
2342  qQRTH2foVmrcGSwTVDAv0VfKKGtosFiO3DzU18ZFWXg=  turkey
2343  yWFI4tbzaR7xLuV97IX0viSWlEFtyHCVmSzUt1zVOww=  turkey

[2344 rows x 2 columns]
165752
                                           userid country
0                                      1610785728  turkey
1    ESDjEFVwJBaormOiJ6aBBhB2pa4BXOFIsTcPCruD1cg=  turkey
2                              809027506930089984  turkey
3    KJkScVokX3luubomolD1TKwE9Jsj3dN+mzQngJcbYHY=  turkey
4                              710231071300972544  turkey
..                                            ...     ...
937  lt97fNgkxpPT4S6q2GAjdYEHYicloFMiDukPXBp6Pj0=  turkey
938                            926767934990635008  turkey
939    ZUZUAsp8c4ZKUBsmY1WKAXhZjwlNp6+tZPMR5GRjA=  turkey
940                                    2871995935  turkey
941                            820348301434388481  turkey

[942 rows x 2 columns]
166694
                                            userid country
0     ViT1StGlEgQE74tYIXup8rS7gyADbTrUcqNTPYYESds=  turkey
1                                        378546115  turkey
2                                       1512112903  turkey
3                                        216749686  turkey
4                                       4709160383  turkey
...                                            ...     ...
1821  JE635xPqNgKcHLkezR5XsgnMM4ntNOhsbgJk3Ey7tRI=  turkey
1822                                    2570905323  turkey
1823                                    2615652662  turkey
1824   9E7gp4MZu8zVihB+oyPFgEWj9CkPI9udVTarOcpPko=  turkey
1825   PwRodTuboET3RbBq5pcQYczLI7LVktAgOwx7A4+X4c=  turkey

[1826 rows x 2 columns]
168520
                                            userid country
0      yrXACLdGlS0vfceEhhaHgjZ0aYu1oCepgjSOVXcSDM=  turkey
1        Vu1mk72dJXH07SUzNDh+vfATnzfwv817oH0QWCAA=  turkey
2     WKaU+tsQAofM2Vc2q7SAcZ5HolkEV2RD4iBVNkdEBgU=  turkey
3     1W9KXRrG2CMRo9ap84INr9H3JNHEhk2puJmlSScJMcY=  turkey
4      vLYW+4YIMI+mL3QMtSKegs4Y4ItCkS6qLGy7iwpeoU=  turkey
...                                            ...     ...
2169    FhrhnFCdIBzNu6T+AAgjYZXEymrxFiRheGbUzcvTo=  turkey
2170                            861827720325591040  turkey
2171                                    4001201595  turkey
2172                            826120755322691584  turkey
2173                            810201871700918272  turkey

[2174 rows x 2 columns]
170694
                                            userid country
0      cwhl0K17G02oajS1uCVkIdXpJsZBRNMvGMsR47pjag=  turkey
1                               967513334223376384  turkey
2       S1Ud5l07axa4F46z+ov0WUkIQ1vJDG2DWwyF0Lqog=  turkey
3     z0oFc+Sq8SjwuOGOuCxLh6ESWlSoK2Lr3loXQD1z1YQ=  turkey
4       wOKgGLSNDWqD4ibrxYngSNwpXDBfOkGLilmhXJ3xE=  turkey
...                                            ...     ...
1830   nCnSP8OTFabNDqAd60n8pZeR0mRlvVvW3+y29d84sk=  turkey
1831   zuP0S4y8UEfIgNbdLiUi5ZHZN+FmcTcsezz+3+UuRI=  turkey
1832                                    2240658110  turkey
1833  1XkMwAfU03hFTekwL7InEGYD86yVM3sGBXzsJGiqUDo=  turkey
1834  yAtCZHrfq71yMwMVr3NFxQpv1KVDdV4p93+KXFeMAFg=  turkey

[1835 rows x 2 columns]
172529

                                            userid country
0                               929806389870022656  turkey
1      wpEe8+9xtl97qPN5lO7VquUm3oVQUxs5YRGEa+PQXk=  turkey
2      25z2p+QEPyDxy5FK1Hf+Dil6MPOOBUKZPqPcen9N90=  turkey
3     ITvQQ1e8uh+vK6BYRULwcJXpZAYoL5dsZQaeVcQT+nI=  turkey
4                                       1479215311  turkey
...                                            ...     ...
1585   VcZarapCgsBbjpC+ptDW0XSOhcWmRrsj0FMUGLa20U=  turkey
1586  k2PMEbrQDp4EHf9x47kWBsVNMeinH97hu6uoEDHLQBM=  turkey
1587  TikE+Blbf32exEDoO6eSIWagJXrKx9UOX37WYh8eIE8=  turkey
1588   VS51nrV+Fpi8ozQIKv+hjRmnmptrrtruYNIcWWcge8=  turkey
1589   1hMJ+SlAoniLQBJa9dRZzlWZ2NQMJfslsCwODS7vMs=  turkey

[1590 rows x 2 columns]
174119
                                            userid country
0                                       2256740149  turkey
1     tNpFnm2rii0FUhLfmZeWbIINzOf0sDlIhr4eRBR0we4=  turkey
2                                       1610785728  turkey
3                                       2741775742  turkey
4       6G6SsXFeBWRQXawRXJn7CnRh1DGdIu98PF4ZXuPf8=  turkey
...                                            ...     ...
1614  e6AKqTHnj3VlyVsKLWieZKt1Y5S3UQHnDn4kYaFeJK4=  turkey
1615   x0B9T4xkq5Zdxwj2dBAOIwqkTwOJjMHHV2ZJqjWb7E=  turkey
1616  0UOtaqhgsOLAVzqTJnKcOODm5VxzGfxQXqK8jevj0jo=  turkey
1617  BSRbH7+WpDxEJ0zqz58WjEs8YISfgjJ5pcqJIXRABUk=  turkey
1618  oxVWisWMooMqIeDoz+m3LSL1ebyAQ0tLEZo77JKFzag=  turkey

[1619 rows x 2 columns]
175738
                                            userid country
0                                        635452378  turkey
1                                        257461245  turkey
2                                       2202308074  turkey
3                                        326452527  turkey
4                                        315764908  turkey
...                                            ...     ...
1923  lIYbBoLbAJ2MTYlXTb6IBMJzMa5ZxJ43bndICot0ZcI=  turkey
1924    UNErnC8Q5pcROxkeCCoPEyI+EbkR13aEs94X++3y4=  turkey
1925  cHtcST69OGbivZFikXFMAyQ+eHOR5w0LnffPPbiuPxU=  turkey
1926    7cFPPgXxAe63D5Fi2mr1ohvzv67Pw2RmjIIwWtOvk=  turkey
1927   lu9FmDSwcnIjVJ1uEgkgmznN3P57xA7Ir6IyyT7mFM=  turkey

[1928 rows x 2 columns]
177666
uae
['_uae_IOactors.csv', '_uae_egypt_IOactors.csv', '_uae_egypt_IOactors_1.csv', '_uae_IOactors_1.csv']
                                            userid country
0      gImO7fATUVOh6vLt9DYhsOZWlL9Wsvo2fauUCSvPN4=     uae
1     t0CFzCOo2MAIQqKDToXxhRLXZziJTTcMGRMkqG0cTuU=     uae
2       vmM2iVExjD0PAHJIX58cwWd1otT1B2+XZrbKVD7uI=     uae
3      a5bU4w32vGj+XR0yQr4HYBk0JTZrTLG5rIV9R+6CzM=     uae
4      pUkqKjrVhpQAMocfu4aSDjihmkqDFHPGU44kq5Ljp8=     uae
...                                            ...     ...
2872  QGYh9PmzOM5bvCoLF6vjoO2J1S8QJ9BtzZ0n0mWFiI8=     uae
2873  wdgVUwpZV+u33Z8hptRVJ13NuKMcGRXg2l45WLwmVFc=     uae
2874    cQKqCRk4d4wQOCGGc+wg9nmmCcRNzSSTdW7msB8Xs=     uae
2875   2b841chjkigd1XKlTBs3Pjnt1qpRK324QbZRFjKlOI=     uae
2876   9ZQmWgsqQ2tDZUc7V49MeV7N0mCYWkmkQS0ITybBg8=     uae

[2877 rows x 2 columns]
180543
                                           userid country
0                              869180784728518656     uae
1      EEstHwOwHRNWIefhWQhr1jlKZoxl+hpb51++13+E4=     uae
2     sAMCJGsRrL1AuWEMMJ183Wd1BlP0GKxQft7RCIVQio=     uae
3     zSQFG4VqDBoxFDzNteoCcy3JuDNfWjllIDMHQkGBzg=     uae
4                              981925161271250945     uae
..                                            ...     ...
220                                    1139364402     uae
221                                     989808386     uae
222                                    4558713094     uae
223    hd92rmFmAkVjMKMDv807KZOTx79KBuXAWXpl1daL8=     uae
224  3f3uWoPaOVxzGz9bqFDO8FLTePIIduMObqNs4oN6eFs=     uae

[225 rows x 2 columns]
180768
                                           userid country
0                              869180784728518656     uae
1      EEstHwOwHRNWIefhWQhr1jlKZoxl+hpb51++13+E4=     uae
2     sAMCJGsRrL1AuWEMMJ183Wd1BlP0GKxQft7RCIVQio=     uae
3     zSQFG4VqDBoxFDzNteoCcy3JuDNfWjllIDMHQkGBzg=     uae
4                              981925161271250945     uae
..                                            ...     ...
220                                    1139364402     uae
221                                     989808386     uae
222                                    4558713094     uae
223    hd92rmFmAkVjMKMDv807KZOTx79KBuXAWXpl1daL8=     uae
224  3f3uWoPaOVxzGz9bqFDO8FLTePIIduMObqNs4oN6eFs=     uae

[225 rows x 2 columns]
180993
                                            userid country
0      gImO7fATUVOh6vLt9DYhsOZWlL9Wsvo2fauUCSvPN4=     uae
1     t0CFzCOo2MAIQqKDToXxhRLXZziJTTcMGRMkqG0cTuU=     uae
2       vmM2iVExjD0PAHJIX58cwWd1otT1B2+XZrbKVD7uI=     uae
3      a5bU4w32vGj+XR0yQr4HYBk0JTZrTLG5rIV9R+6CzM=     uae
4      pUkqKjrVhpQAMocfu4aSDjihmkqDFHPGU44kq5Ljp8=     uae
...                                            ...     ...
2872  QGYh9PmzOM5bvCoLF6vjoO2J1S8QJ9BtzZ0n0mWFiI8=     uae
2873  wdgVUwpZV+u33Z8hptRVJ13NuKMcGRXg2l45WLwmVFc=     uae
2874    cQKqCRk4d4wQOCGGc+wg9nmmCcRNzSSTdW7msB8Xs=     uae
2875   2b841chjkigd1XKlTBs3Pjnt1qpRK324QbZRFjKlOI=     uae
2876   9ZQmWgsqQ2tDZUc7V49MeV7N0mCYWkmkQS0ITybBg8=     uae

[2877 rows x 2 columns]
183870
uae_egypt
['_uae_egypt_IOactors.csv', '_uae_egypt_IOactors_1.csv']
                                           userid    country
0                              869180784728518656  uae_egypt
1      EEstHwOwHRNWIefhWQhr1jlKZoxl+hpb51++13+E4=  uae_egypt
2     sAMCJGsRrL1AuWEMMJ183Wd1BlP0GKxQft7RCIVQio=  uae_egypt
3     zSQFG4VqDBoxFDzNteoCcy3JuDNfWjllIDMHQkGBzg=  uae_egypt
4                              981925161271250945  uae_egypt
..                                            ...        ...
220                                    1139364402  uae_egypt
221                                     989808386  uae_egypt
222                                    4558713094  uae_egypt
223    hd92rmFmAkVjMKMDv807KZOTx79KBuXAWXpl1daL8=  uae_egypt
224  3f3uWoPaOVxzGz9bqFDO8FLTePIIduMObqNs4oN6eFs=  uae_egypt

[225 rows x 2 columns]
184095
                                           userid    country
0                              869180784728518656  uae_egypt
1      EEstHwOwHRNWIefhWQhr1jlKZoxl+hpb51++13+E4=  uae_egypt
2     sAMCJGsRrL1AuWEMMJ183Wd1BlP0GKxQft7RCIVQio=  uae_egypt
3     zSQFG4VqDBoxFDzNteoCcy3JuDNfWjllIDMHQkGBzg=  uae_egypt
4                              981925161271250945  uae_egypt
..                                            ...        ...
220                                    1139364402  uae_egypt
221                                     989808386  uae_egypt
222                                    4558713094  uae_egypt
223    hd92rmFmAkVjMKMDv807KZOTx79KBuXAWXpl1daL8=  uae_egypt
224  3f3uWoPaOVxzGz9bqFDO8FLTePIIduMObqNs4oN6eFs=  uae_egypt

[225 rows x 2 columns]
184320
venezuela
['_venezuela_IOactors.csv', '_venezuela_IOactors_1.csv']
                                           userid    country
0    9TTUuUnVBwPxbCeayXuIBEv6VccL29fHKg3g1UXYOUs=  venezuela
1                                        61201840  venezuela
2                                       254088115  venezuela
3      U3MUqfd4PJ50UjvYqRPWFzMwX9Y7Wqt1AVikCuOv0=  venezuela
4                                       179173498  venezuela
..                                            ...        ...
804                                    2871995935  venezuela
805                                    2252188261  venezuela
806  AuVslc5OsfeVbZTO95udeUaOe4c6cp+WpiLJ6D8ZfFU=  venezuela
807   x8W0Bs9gLU4cntzIqCDuiKyENYnKmI473qdTl8TXDE=  venezuela
808  ZWWC+L4NZOsrTbxHvMW0Mz19cSJEjxOyps+SEJVahp8=  venezuela

[809 rows x 2 columns]
185129
                                           userid    country
0    9TTUuUnVBwPxbCeayXuIBEv6VccL29fHKg3g1UXYOUs=  venezuela
1                                        61201840  venezuela
2                                       254088115  venezuela
3      U3MUqfd4PJ50UjvYqRPWFzMwX9Y7Wqt1AVikCuOv0=  venezuela
4                                       179173498  venezuela
..                                            ...        ...
805                                    2871995935  venezuela
806                                    2252188261  venezuela
807  AuVslc5OsfeVbZTO95udeUaOe4c6cp+WpiLJ6D8ZfFU=  venezuela
808   x8W0Bs9gLU4cntzIqCDuiKyENYnKmI473qdTl8TXDE=  venezuela
809  ZWWC+L4NZOsrTbxHvMW0Mz19cSJEjxOyps+SEJVahp8=  venezuela

[810 rows x 2 columns]
185939

In [10]:
IO_actors_master

Empty DataFrame
Columns: [userid, country]
Index: []

In [2]:
import pandas as pd
from pathlib import Path
import os
import numpy as np
import csv
import argparse
import datetime
import sys

In [9]:
folder = '_IOactors'

In [17]:
df = pd.DataFrame(columns=['userid'])
df.to_csv('_masterIOactors.csv', index=False)

In [18]:
s = datetime.datetime.now()
print('----- {} -----\n-- {} -- \n'.format(folder,s))

for file in Path(folder).iterdir():
    if file.name.endswith('.csv'):
        print('Reading {}'.format(file))
        df = pd.read_csv(file)
        df.userid = df.userid.apply(str)
        df.to_csv('_masterIOactors.csv', mode='a', header=False, index=False)

----- _IOactors -----
-- 2021-02-25 06:56:13.462453 --

Reading _IOactors/_turkey_IOactors_2.csv
Reading _IOactors/_turkey_IOactors_8.csv
Reading _IOactors/_saudi_arabia_IOactors_12.csv
Reading _IOactors/_egypt_IOactors.csv
Reading _IOactors/_saudi_arabia_IOactors_15.csv
Reading _IOactors/_uae_IOactors.csv
Reading _IOactors/_saudi_arabia_IOactors_7.csv
Reading _IOactors/_serbia_IOactors_11.csv
Reading _IOactors/_indonesia_IOactors.csv
Reading _IOactors/_saudi_arabia_IOactors_8.csv
Reading _IOactors/_serbia_IOactors_1.csv
Reading _IOactors/_china_IOactors.csv
Reading _IOactors/_bangladesh_IOactors.csv
Reading _IOactors/_serbia_IOactors_5.csv
Reading _IOactors/_saudi_arabia_IOactors_6.csv
Reading _IOactors/_serbia_IOactors_9.csv
Reading _IOactors/_saudi_arabia_IOactors_11.csv
Reading _IOactors/_serbia_IOactors_10.csv
Reading _IOactors/_serbia_IOactors_15.csv
Reading _IOactors/_turkey_IOactors_15.csv
Reading _IOactors/_iran_IOactors.csv
Reading _IOactors/_turkey_IOactors_14.csv
Reading _IOactors/_turkey_IOactors_9.csv
Reading _IOactors/_turkey_IOactors_6.csv
Reading _IOactors/_cuba_IOactors.csv
Reading _IOactors/_serbia_IOactors_13.csv
Reading _IOactors/_spain_IOactors.csv
Reading _IOactors/_serbia_IOactors_2.csv
Reading _IOactors/_serbia_IOactors_4.csv
Reading _IOactors/_saudi_arabia_IOactors_14.csv
Reading _IOactors/_uae_egypt_IOactors.csv
Reading _IOactors/_saudi_arabia_IOactors_9.csv
Reading _IOactors/_serbia_IOactors_8.csv
Reading _IOactors/_saudi_arabia_IOactors_3.csv
Reading _IOactors/_serbia_IOactors_7.csv
Reading _IOactors/_turkey_IOactors_10.csv
Reading _IOactors/_russia_IOactors.csv
Reading _IOactors/_turkey_IOactors_1.csv
Reading _IOactors/_serbia_IOactors_6.csv
Reading _IOactors/_saudi_arabia_IOactors_10.csv
Reading _IOactors/_saudi_arabia_IOactors_2.csv
Reading _IOactors/_catalonia_IOactors.csv
Reading _IOactors/_turkey_IOactors_11.csv
Reading _IOactors/_turkey_IOactors_5.csv
Reading _IOactors/_saudi_arabia_IOactors_13.csv
Reading _IOactors/_saudi_arabia_IOactors_4.csv
Reading _IOactors/_ecuador_IOactors.csv
Reading _IOactors/_saudi_arabia_IOactors_5.csv
Reading _IOactors/_turkey_IOactors_3.csv
Reading _IOactors/_saudi_arabia_IOactors_1.csv
Reading _IOactors/_serbia_IOactors_14.csv
Reading _IOactors/_honduras_IOactors.csv
Reading _IOactors/_serbia_IOactors_12.csv
Reading _IOactors/_turkey_IOactors_13.csv
Reading _IOactors/_serbia_IOactors_3.csv
Reading _IOactors/_turkey_IOactors_4.csv
Reading _IOactors/_thailand_IOactors.csv
Reading _IOactors/_turkey_IOactors_7.csv
Reading _IOactors/_turkey_IOactors_12.csv
Reading _IOactors/_venezuela_IOactors.csv

In [32]:
ioActors = pd.read_csv('_masterIOactors.csv')
ioActors = ioActors.drop_duplicates()
ioActors

                                              userid
0       E9ZoRqZtcBataiZAYmI5Hy+PGq8JvNo6Pgkgkh37HtM=
1                                         2765536403
2                                         4609724483
3       D4Y5diz3k4kq2S5HnW0wGYRaO3Jys3dW6Q6jPwn6gBI=
4        uJ+l8rnMPJ0JF7MOEDadqtd5MipV29uOG3xUAbGldg=
...                                              ...
137601                            821765954426335234
137602                            823291980025303040
137612  AuVslc5OsfeVbZTO95udeUaOe4c6cp+WpiLJ6D8ZfFU=
137613   x8W0Bs9gLU4cntzIqCDuiKyENYnKmI473qdTl8TXDE=
137614  ZWWC+L4NZOsrTbxHvMW0Mz19cSJEjxOyps+SEJVahp8=

[59193 rows x 1 columns]

In [33]:
masterUID = pd.read_csv('masterUIDS_Oct2020.csv')
masterUID = masterUID[masterUID['id']!='userid']
masterUID

                                                 id     country
1       ygQRwhQRrh1+6N7J6IMFnzWgqUGimWqg0KZptLpxDY=  bangladesh
2      0OvJRirnL32w7blCoMRthk30yPlXapfIPFac4Eyje0k=  bangladesh
3        UOYzWkr60fJQXg134s861VR6yVN8ECzm9Onrnvu5s=  bangladesh
4      5yP0DlSBuPEQJIOdniuznIo1Roucbu6jVHZNUnHcei0=  bangladesh
5       QGdKV23i9r+ocu2cySQC8J8O0BJmxQLM8n4xB6RQg8=  bangladesh
...                                             ...         ...
76027   +kqOi5mumxWs5piGwNwRZoHuMZ9Z4Q2Hl1aQ44IWhA=   venezuela
76028  pOkiiDsJkTR8+tURK+3xX+CjZNA9quEVtlZ8kEHmyIA=   venezuela
76029  VgXpbrUboenOjSquH9hgdB7Eg5xHv4P9T9qEu258IIc=   venezuela
76030   SNHdSFMsvkTihsKIYsaVu9CHQNlDjRQbxrkY+Plt1Y=   venezuela
76031  CDqzv0hElUsI40Sjw9td2QPe0XXfsjJKOhay19pX+PQ=   venezuela

[76015 rows x 2 columns]

In [34]:
len(ioActors)/len(masterUID)

0.7787015720581464

In [35]:
ioActors = pd.merge(ioActors, masterUID, left_on='userid', right_on='id', how='left')
ioActors

,userid,id,country
0,E9ZoRqZtcBataiZAYmI5Hy+PGq8JvNo6Pgkgkh37HtM=,E9ZoRqZtcBataiZAYmI5Hy+PGq8JvNo6Pgkgkh37HtM=,turkey
1,2765536403,2765536403,turkey
2,4609724483,4609724483,turkey
3,D4Y5diz3k4kq2S5HnW0wGYRaO3Jys3dW6Q6jPwn6gBI=,D4Y5diz3k4kq2S5HnW0wGYRaO3Jys3dW6Q6jPwn6gBI=,turkey
4,uJ+l8rnMPJ0JF7MOEDadqtd5MipV29uOG3xUAbGldg=,uJ+l8rnMPJ0JF7MOEDadqtd5MipV29uOG3xUAbGldg=,turkey
...,...,...,...
59188,821765954426335234,821765954426335234,venezuela
59189,823291980025303040,823291980025303040,venezuela
59190,AuVslc5OsfeVbZTO95udeUaOe4c6cp+WpiLJ6D8ZfFU=,AuVslc5OsfeVbZTO95udeUaOe4c6cp+WpiLJ6D8ZfFU=,venezuela
59191,x8W0Bs9gLU4cntzIqCDuiKyENYnKmI473qdTl8TXDE=,x8W0Bs9gLU4cntzIqCDuiKyENYnKmI473qdTl8TXDE=,venezuela
59192,ZWWC+L4NZOsrTbxHvMW0Mz19cSJEjxOyps+SEJVahp8=,ZWWC+L4NZOsrTbxHvMW0Mz19cSJEjxOyps+SEJVahp8=,venezuela

In [39]:
ioActors = ioActors.userid.apply(str)
ioActors.country.value_counts()

china           24237
saudi_arabia     6237
serbia           5243
turkey           4937
iran             4709
russia           3684
uae              2779
egypt            1805
honduras         1366
venezuela         786
indonesia         527
cuba              453
ecuador           375
uae_egy           206
spain             148
thailand           76
catalonia          39
bangladesh          6
Name: country, dtype: int64

In [42]:
ioActors = ioActors[['userid', 'country']]
ioActors

KeyError: "None of [Index(['userid', 'country'], dtype='object')] are in the [index]"

In [45]:
ioActors.to_csv('_masterIOactors.csv', index =False)
ioActors

0        E9ZoRqZtcBataiZAYmI5Hy+PGq8JvNo6Pgkgkh37HtM=
1                                          2765536403
2                                          4609724483
3        D4Y5diz3k4kq2S5HnW0wGYRaO3Jys3dW6Q6jPwn6gBI=
4         uJ+l8rnMPJ0JF7MOEDadqtd5MipV29uOG3xUAbGldg=
                             ...
59188                              821765954426335234
59189                              823291980025303040
59190    AuVslc5OsfeVbZTO95udeUaOe4c6cp+WpiLJ6D8ZfFU=
59191     x8W0Bs9gLU4cntzIqCDuiKyENYnKmI473qdTl8TXDE=
59192    ZWWC+L4NZOsrTbxHvMW0Mz19cSJEjxOyps+SEJVahp8=
Name: userid, Length: 59193, dtype: object

In [46]:
country_list = ['bangladesh', 'catalonia', 'ecuador', 'china', 'cuba', 'egypt', 'honduras', 'indonesia', 'iran',
        'russia', 'saudi_arabia', 'serbia', 'spain', 'thailand', 'turkey', 'uae', 'uae_egypt', 'venezuela']

for country in country_list:
    print('reading {}'.format(country))
    df2 = pd.read_pickle('{}_parsed.pkl'.format(country))
    df_inner = pd.merge(df2,ioActors,on='userid', how='inner')
    df_inner.to_csv('_Coordination/{}_IOactor_data.csv'.format(country), index=False)

reading bangladesh

AttributeError: 'DataFrame' object has no attribute '_data'